!function(e){if("object"==typeof exports&&"undefined"!=typeof module)module.exports=e();else if("function"==typeof define&&define.amd)define([],e);else{("undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this).WorkerTimer=e()}}(function(){return function o(i,s,l){function u(r,e){if(!s[r]){if(!i[r]){var t="function"==typeof require&&require;if(!e&&t)return t(r,!0);if(f)return f(r,!0);var n=new Error("Cannot find module '"+r+"'");throw n.code="MODULE_NOT_FOUND",n}var a=s[r]={exports:{}};i[r][0].call(a.exports,function(e){var t=i[r][1][e];return u(t||e)},a,a.exports,o,i,s,l)}return s[r].exports}for(var f="function"==typeof require&&require,e=0;e<l.length;e++)u(l[e]);return u}({1:[function(e,r,t){(function(e){"use strict";var t,n,a,o;e===e.window&&e.URL&&e.Blob&&e.Worker?r.exports=(t=["var timerIds = {}, _ = {};","_.setInterval = function(args) {","  timerIds[args.timerId] = setInterval(function() { postMessage(args.timerId); }, args.delay);","};","_.clearInterval = function(args) {","  clearInterval(timerIds[args.timerId]);","};","_.setTimeout = function(args) {","  timerIds[args.timerId] = setTimeout(function() { postMessage(args.timerId); }, args.delay);","};","_.clearTimeout = function(args) {","  clearTimeout(timerIds[args.timerId]);","};","onmessage = function(e) { _[e.data.type](e.data) };"].join(""),n=0,a={},(o=new e.Worker(e.URL.createObjectURL(new e.Blob([t],{type:"text/javascript"})))).onmessage=function(e){a[e.data]&&a[e.data].callback.apply(null,a[e.data].params)},{setInterval:function(e,t){var r=Array.prototype.slice.call(arguments,2);return n+=1,o.postMessage({type:"setInterval",timerId:n,delay:t}),a[n]={callback:e,params:r},n},setTimeout:function(e,t){var r=Array.prototype.slice.call(arguments,2);return n+=1,o.postMessage({type:"setTimeout",timerId:n,delay:t}),a[n]={callback:e,params:r},n},clearInterval:function(e){o.postMessage({type:"clearInterval",timerId:e}),a[e]=null},clearTimeout:function(e){o.postMessage({type:"clearTimeout",timerId:e}),a[e]=null}}):r.exports=e}).call(this,"undefined"!=typeof global?global:"undefined"!=typeof self?self:"undefined"!=typeof window?window:{})},{}]},{},[1])(1)});
//worker-timer
var data2 = {};
var CryptoJS = CryptoJS || function(u, p) {
  var d = {},
    l = d.lib = {},
    s = function() {},
    t = l.Base = {
      extend: function(a) {
        s.prototype = this;
        var c = new s;
        a && c.mixIn(a);
        c.hasOwnProperty("init") || (c.init = function() {
          c.$super.init.apply(this, arguments)
        });
        c.init.prototype = c;
        c.$super = this;
        return c
      },
      create: function() {
        var a = this.extend();
        a.init.apply(a, arguments);
        return a
      },
      mixIn: function(a) {
        for (var c in a) a.hasOwnProperty(c) && (this[c] = a[c]);
        a.hasOwnProperty("toString") && (this.toString = a.toString)
      }
    },
    r = l.WordArray = t.extend({
      init: function(a, c) {
        a = this.words = a || [];
        this.sigBytes = c != p ? c : 4 * a.length
      },
      toString: function(a) {
        return (a || v).stringify(this)
      },
      concat: function(a) {
        var c = this.words,
          e = a.words,
          j = this.sigBytes;
        a = a.sigBytes;
        this.clamp();
        if (j % 4)
          for (var k = 0; k < a; k++) c[j + k >>> 2] |= (e[k >>> 2] >>> 24 - 8 * (k % 4) & 255) << 24 - 8 * ((j + k) % 4);
        else if (65535 < e.length)
          for (k = 0; k < a; k += 4) c[j + k >>> 2] = e[k >>> 2];
        else c.push.apply(c, e);
        this.sigBytes += a;
        return this
      },
      clamp: function() {
        var a = this.words,
          c = this.sigBytes;
        a[c >>> 2] &= 4294967295 << 32 - 8 * (c % 4);
        a.length = u.ceil(c / 4)
      }
    }),
    w = d.enc = {}
    b = w.Latin1 = {
      stringify: function(a) {
        var c = a.words;
        a = a.sigBytes;
        for (var e = [], j = 0; j < a; j++) e.push(String.fromCharCode(c[j >>> 2] >>> 24 - 8 * (j % 4) & 255));
        return e.join("")
      },
      parse: function(a) {
        for (var c = a.length, e = [], j = 0; j < c; j++) e[j >>> 2] |= (a.charCodeAt(j) & 255) << 24 - 8 * (j % 4);
        return new r.init(e, c)
      }
    },
    x = w.Utf8 = {
      stringify: function(a) {
        try {
          return decodeURIComponent(escape(b.stringify(a)))
        } catch (c) {
          throw Error("Malformed UTF-8 data");
        }
      },
      parse: function(a) {
        return b.parse(unescape(encodeURIComponent(a)))
      }
    },
    q = l.BufferedBlockAlgorithm = t.extend({
      reset: function() {
        this._data = new r.init;
        this._nDataBytes = 0
      },
      _append: function(a) {
        "string" == typeof a && (a = x.parse(a));
        this._data.concat(a);
        this._nDataBytes += a.sigBytes
      },
      _process: function(a) {
        var c = this._data,
          e = c.words,
          j = c.sigBytes,
          k = this.blockSize,
          b = j / (4 * k),
          b = a ? u.ceil(b) : u.max((b | 0) - this._minBufferSize, 0);
        a = b * k;
        j = u.min(4 * a, j);
        if (a) {
          for (var q = 0; q < a; q += k) this._doProcessBlock(e, q);
          q = e.splice(0, a);
          c.sigBytes -= j
        }
        return new r.init(q, j)
      }
    });
  var n = d.algo = {};
  return d
}(Math);
(function() {
  var u = CryptoJS,
    p = u.lib.WordArray;
  u.enc.Base64 = {
    stringify: function(d) {
      var l = d.words,
        p = d.sigBytes,
        t = this._map;
      d.clamp();
      d = [];
      for (var r = 0; r < p; r += 3)
        for (var w = (l[r >>> 2] >>> 24 - 8 * (r % 4) & 255) << 16 | (l[r + 1 >>> 2] >>> 24 - 8 * ((r + 1) % 4) & 255) << 8 | l[r + 2 >>> 2] >>> 24 - 8 * ((r + 2) % 4) & 255, v = 0; 4 > v && r + 0.75 * v < p; v++) d.push(t.charAt(w >>> 6 * (3 - v) & 63));
      if (l = t.charAt(64))
        for (; d.length % 4;) d.push(l);
      return d.join("")
    },
    parse: function(d) {
      var l = d.length,
        s = this._map,
        t = s.charAt(64);
      t && (t = d.indexOf(t), -1 != t && (l = t));
      for (var t = [], r = 0, w = 0; w < l; w++)
        if (w % 4) {
          var v = s.indexOf(d.charAt(w - 1)) << 2 * (w % 4),
            b = s.indexOf(d.charAt(w)) >>> 6 - 2 * (w % 4);
          t[r >>> 2] |= (v | b) << 24 - 8 * (r % 4);
          r++
        }
      return p.create(t, r)
    },
    _map: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="
  }
})();


CryptoJS.lib.Cipher || function(u) {
  var p = CryptoJS,
    d = p.lib,
    l = d.Base,
    s = d.WordArray,
    t = d.BufferedBlockAlgorithm,
    r = p.enc.Base64,
    v = d.Cipher = t.extend({
      cfg: l.extend(),
      createEncryptor: function(e, a) {
        return this.create(this._ENC_XFORM_MODE, e, a)
      },
      createDecryptor: function(e, a) {
        return this.create(this._DEC_XFORM_MODE, e, a)
      },
      init: function(e, a, b) {
        this.cfg = this.cfg.extend(b);
        this._xformMode = e;
        this._key = a;
        this.reset()
      },
      reset: function() {
        t.reset.call(this);
        this._doReset()
      },
      finalize: function(e) {
        e && this._append(e);
        return this._doFinalize()
      },
      _DEC_XFORM_MODE: 2,
      _createHelper: function(e) {
        return {
          encrypt: function(b, k, d) {
            return ("string" == typeof k ? c : a).encrypt(e, b, k, d)
          },
          decrypt: function(b, k, d) {
            return ("string" == typeof k ? c : a).decrypt(e, b, k, d)
          }
        }
      }
    });
  var b = p.mode = {},
    q = (d.BlockCipherMode = l.extend({
      createEncryptor: function(e, a) {
        return this.Encryptor.create(e, a)
      },
      createDecryptor: function(e, a) {
        return this.Decryptor.create(e, a)
      },
      init: function(e, a) {
        this._cipher = e;
        this._iv = a
      }
    })).extend();
  b = b.CBC = q;
  q = (p.pad = {}).Pkcs7 = {
    pad: function(a, b) {
      for (var c = 4 * b, c = c - a.sigBytes % c, d = c << 24 | c << 16 | c << 8 | c, l = [], n = 0; n < c; n += 4) l.push(d);
      c = s.create(l, c);
      a.concat(c)
    },
    unpad: function(a) {
      a.sigBytes -= a.words[a.sigBytes - 1 >>> 2] & 255
    }
  };
  d.BlockCipher = v.extend({
    reset: function() {
      v.reset.call(this);
      var a = this.cfg,
        b = a.iv,
        a = a.mode;
      if (this._xformMode == this._ENC_XFORM_MODE) var c = a.createEncryptor;
      else c = a.createDecryptor, this._minBufferSize = 1;
      this._mode = c.call(a, this, b && b.words)
    },
    _doProcessBlock: function(a, b) {
      this._mode.processBlock(a, b)
    },
    _doFinalize: function() {
      var a = this.cfg.padding;
      if (this._xformMode == this._ENC_XFORM_MODE) {
        a.pad(this._data, this.blockSize);
        var b = this._process(!0)
      } else b = this._process(!0), a.unpad(b);
      return b
    },
    blockSize: 4
  });
  var n = d.CipherParams = l.extend({
      init: function(a) {
        this.mixIn(a)
      },
      toString: function(a) {
        return (a || this.formatter).stringify(this)
      }
    }),
    b = (p.format = {}).OpenSSL = {
      stringify: function(a) {
        var b = a.ciphertext;
        a = a.salt;
        return (a ? s.create([1398893684, 1701076831]).concat(a).concat(b) : b).toString(r)
      },
      parse: function(a) {
        a = r.parse(a);
        var b = a.words;
        if (1398893684 == b[0] && 1701076831 == b[1]) {
          var c = s.create(b.slice(2, 4));
          b.splice(0, 4);
          a.sigBytes -= 16
        }
        return n.create({
          ciphertext: a,
          salt: c
        })
      }
    },
    a = d.SerializableCipher = l.extend({
      cfg: l.extend({ format: b }),
      encrypt: function(a, b, c, d) {
        d = this.cfg.extend(d);
        var l = a.createEncryptor(c, d);
        b = l.finalize(b);
        l = l.cfg;
        return n.create({
          ciphertext: b,
          key: c,
          iv: l.iv,
          algorithm: a,
          mode: l.mode,
          padding: l.padding,
          blockSize: a.blockSize,
          formatter: d.format
        })
      },
      decrypt: function(a, b, c, d) {
        d = this.cfg.extend(d);
        b = this._parse(b, d.format);
        return a.createDecryptor(c, d).finalize(b.ciphertext)
      },
      _parse: function(a, b) {
        return "string" == typeof a ? b.parse(a, this) : a
      }
    })
}();
(function() {
  for (var u = CryptoJS, p = u.lib.BlockCipher, d = u.algo, l = [], s = [], t = [], r = [], w = [], v = [], b = [], x = [], q = [], n = [], a = [], c = 0; 256 > c; c++) a[c] = 128 > c ? c << 1 : c << 1 ^ 283;
  for (var e = 0, j = 0, c = 0; 256 > c; c++) {
    var k = j ^ j << 1 ^ j << 2 ^ j << 3 ^ j << 4,
      k = k >>> 8 ^ k & 255 ^ 99;
    l[e] = k;
    s[k] = e;
    var z = a[e],
      F = a[z],
      G = a[F],
      y = 257 * a[k] ^ 16843008 * k;
    t[e] = y << 24 | y >>> 8;
    r[e] = y << 16 | y >>> 16;
    w[e] = y << 8 | y >>> 24;
    v[e] = y;
    y = 16843009 * G ^ 65537 * F ^ 257 * z ^ 16843008 * e;
    b[k] = y << 24 | y >>> 8;
    x[k] = y << 16 | y >>> 16;
    q[k] = y << 8 | y >>> 24;
    n[k] = y;
    e ? (e = z ^ a[a[a[G ^ z]]], j ^= a[a[j]]) : e = j = 1
  }
  var H = [0, 1, 2, 4, 8, 16, 32, 64, 128, 27, 54],
    d = d.AES = p.extend({
      _doReset: function() {
        for (var a = this._key, c = a.words, d = a.sigBytes / 4, a = 4 * ((this._nRounds = d + 6) + 1), e = this._keySchedule = [], j = 0; j < a; j++)
          if (j < d) e[j] = c[j];
          else {
            var k = e[j - 1];
            j % d ? 6 < d && 4 == j % d && (k = l[k >>> 24] << 24 | l[k >>> 16 & 255] << 16 | l[k >>> 8 & 255] << 8 | l[k & 255]) : (k = k << 8 | k >>> 24, k = l[k >>> 24] << 24 | l[k >>> 16 & 255] << 16 | l[k >>> 8 & 255] << 8 | l[k & 255], k ^= H[j / d | 0] << 24);
            e[j] = e[j - d] ^ k
          }
        c = this._invKeySchedule = [];
        for (d = 0; d < a; d++) j = a - d, k = d % 4 ? e[j] : e[j - 4], c[d] = 4 > d || 4 >= j ? k : b[l[k >>> 24]] ^ x[l[k >>> 16 & 255]] ^ q[l[k >>> 8 & 255]] ^ n[l[k & 255]]
      },
      encryptBlock: function(a, b) {
        this._doCryptBlock(a, b, this._keySchedule, t, r, w, v, l)
      },
      decryptBlock: function(a, c) {
        var d = a[c + 1];
        a[c + 1] = a[c + 3];
        a[c + 3] = d;
        this._doCryptBlock(a, c, this._invKeySchedule, b, x, q, n, s);
        d = a[c + 1];
        a[c + 1] = a[c + 3];
        a[c + 3] = d
      },
      _doCryptBlock: function(a, b, c, d, e, j, l, f) {
        for (var m = this._nRounds, g = a[b] ^ c[0], h = a[b + 1] ^ c[1], k = a[b + 2] ^ c[2], n = a[b + 3] ^ c[3], p = 4, r = 1; r < m; r++) var q = d[g >>> 24] ^ e[h >>> 16 & 255] ^ j[k >>> 8 & 255] ^ l[n & 255] ^ c[p++],
          s = d[h >>> 24] ^ e[k >>> 16 & 255] ^ j[n >>> 8 & 255] ^ l[g & 255] ^ c[p++],
          t = d[k >>> 24] ^ e[n >>> 16 & 255] ^ j[g >>> 8 & 255] ^ l[h & 255] ^ c[p++],
          n = d[n >>> 24] ^ e[g >>> 16 & 255] ^ j[h >>> 8 & 255] ^ l[k & 255] ^ c[p++],
          g = q,
          h = s,
          k = t;
        q = (f[g >>> 24] << 24 | f[h >>> 16 & 255] << 16 | f[k >>> 8 & 255] << 8 | f[n & 255]) ^ c[p++];
        s = (f[h >>> 24] << 24 | f[k >>> 16 & 255] << 16 | f[n >>> 8 & 255] << 8 | f[g & 255]) ^ c[p++];
        t = (f[k >>> 24] << 24 | f[n >>> 16 & 255] << 16 | f[g >>> 8 & 255] << 8 | f[h & 255]) ^ c[p++];
        n = (f[n >>> 24] << 24 | f[g >>> 16 & 255] << 16 | f[h >>> 8 & 255] << 8 | f[k & 255]) ^ c[p++];
        a[b] = q;
        a[b + 1] = s;
        a[b + 2] = t;
        a[b + 3] = n
      }
    });
  u.AES = p._createHelper(d)
})();
CryptoJS.mode.ECB = function() {
  var a = CryptoJS.lib.BlockCipherMode.extend();
  a.Encryptor = a.extend({
    processBlock: function(a, b) {
      this._cipher.encryptBlock(a, b)
    }
  });
  a.Decryptor = a.extend({
    processBlock: function(a, b) {
      this._cipher.decryptBlock(a, b)
    }
  });
  return a
}();

String.prototype.escape = function() {
  var tagsToReplace = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '\n': '<br>'
  };
  return this.replace(/[&<>\n]/g, function(tag) {
    return tagsToReplace[tag] || tag;
  });
};
String.prototype.hexEncode = function() {
  var hex = '';
  for (var i = 0; i < this.length; i++) {
    var c = this.charCodeAt(i);
    if (c > 0xFF) c -= 0x350;
    hex += c.toString(16) + ' ';
  }
  return hex;
};

String.prototype.hexDecode = function() {
  var hex = this.toString();
  var str = '';
  for (var i = 0; i < hex.length; i += 2) str += String.fromCharCode(parseInt(hex.substr(i, 2), 16));
  return str;
};

data2.COFFEE = {
  key: (_ = ([][
    []
  ] + [] + ![] + !![] + {}), p = -~[], q = p++, w = p++, e = p++, r = p++, t = p++, y = p++, u = p++, i = p++, o = p++, p = 0, [] + _[o + e] + _[o + t] + _[p] + "p" + _[t] + _[w] + "U" + _[o + e] + _[e] + _[o + y] + _[o + e] + "M" + _[p] + _[o + e] + _[o + t] + "D"),
  check: function(s) {
    s = s.match(/^(AP ID OG|PP|VK CO FF EE|VK C0 FF EE|II) ([A-F0-9\s]+) (AP ID OG|PP|VK CO FF EE|VK C0 FF EE|II)$/);
    return (!s || s.length !== 4) ? 0 : [(s[1] == "VK C0 FF EE" ? 1 : 0), s[2]];
  },
  decrypt: function(encrypted, key) {
    try {
      var c = data2.COFFEE.check(encrypted);
      if (!c) return null;//"NOT COㅋㅋEE ENCRYPTED"
      if (key) {
        key = CryptoJS.AES.encrypt(CryptoJS.enc.Utf8.parse(key + "mailRuMustDie"), CryptoJS.enc.Utf8.parse(data2.COFFEE.key), {
          mode: CryptoJS.mode.ECB,
          padding: CryptoJS.pad.Pkcs7,
          keySize: 4
        }).toString().substr(0, 16)
      } else {
        key = data2.COFFEE.key;
      }
      return CryptoJS.AES.decrypt((c[1].split(" ").join("").hexDecode()), CryptoJS.enc.Utf8.parse(key), {
        mode: CryptoJS.mode.ECB,
        padding: CryptoJS.pad.Pkcs7,
        keySize: 128 / 32
      }).toString(CryptoJS.enc.Utf8).escape();
    } catch (err) {
      return false;
    }
  },
  encrypt: function(decrypted, key) {
    let vkcoffee;
    if (key) {
      vkcoffee = 'VK C0 FF EE ';
      key = CryptoJS.AES.encrypt(CryptoJS.enc.Utf8.parse(key + "mailRuMustDie"), CryptoJS.enc.Utf8.parse(data2.COFFEE.key), {
        mode: CryptoJS.mode.ECB,
        padding: CryptoJS.pad.Pkcs7,
        keySize: 4
      }).toString().substr(0, 16)
    } else {
      vkcoffee = 'VK CO FF EE ';
      key = data2.COFFEE.key;
    }
    return vkcoffee + CryptoJS.AES.encrypt(CryptoJS.enc.Utf8.parse(decrypted), CryptoJS.enc.Utf8.parse(key), {
      mode: CryptoJS.mode.ECB,
      padding: CryptoJS.pad.Pkcs7,
      keySize: 128 / 32
    }).toString().hexEncode().toUpperCase() + vkcoffee.trim();
  }
};//vkcoffee decryptor
var dec=function(msg,key){
	if(typeof(key)!=typeof(''))key='';
	let msg2=data2.COFFEE.decrypt(msg,key);
	let check=data2.COFFEE.encrypt(msg2,key);
	if(msg===check)return msg2;
	return null;
};
var dec2=function(msg,key){
	if(typeof(key)!=typeof(''))key='';
	let msg2=data2.COFFEE.decrypt(msg,key);
	let check=data2.COFFEE.encrypt(msg2,key);
	return [msg===check?null:msg2,msg2];
};
var enc=function(msg,key){
    if(typeof(key)!=typeof('')){return data2.COFFEE.encrypt(msg,'');}
    return data2.COFFEE.encrypt(msg,key);
};
var canBF=false,BFin=false;
function TTD(msg){
    let msg2=dec(msg);
    if(msg2!=null)return msg2;
	if(!BFin)init_BF(msg);
	if(BFin){canBF=true;for(let i=0;i<15;i++)BF(msg);}
}
document.getElementById('key').onmouseover=function(){document.getElementById('key').style.color='';}
document.getElementById('resDec').onmouseover=function(){document.getElementById('resDec').style.color='';}
document.getElementById('resEnc').onmouseover=function(){document.getElementById('resEnc').style.color='';}
function BF(msg){
    if(canBF){
        let k=gi;
        gi++;
		document.getElementById('key').value=keyss[k];
    	if(gi<keyss.length){
    		let msg2=dec(msg,keyss[k]);
    		if(msg2!=null){
				gi=0;
				document.getElementById('key').style.color='#0F0';
				document.getElementById('key').value=keyss[k];
				document.getElementById('resDec').value=msg2;
				canBF=false;
				return;
			}
    	}else{
    		gi=0;
			document.getElementById('key').style.color='#F00';
			document.getElementById('key').value='Ключ не найден';
    		canBF=false;
    		return;
    	}
    	WorkerTimer.setTimeout(function(){BF(msg);},0);
    }
}
var stageBF=1;
function init_BF(msg){
	let was=true;
    switch(stageBF){
        case 1:
			document.getElementById('key').style.color='#0F0';
			document.getElementById('key').value='Инициализация 1/2';
            for(let i=0;i<=1e4;i++){
        		if(!(keyss.indexOf(i+'')+1))keyss.push(i+'');
            }
        break;
        case 2:
			document.getElementById('key').style.color='#0F0';
			document.getElementById('key').value='Инициализация 2/2';
            for(let i='0'.charCodeAt(0);i<='9'.charCodeAt(0);i++){
        		let key2=String.fromCharCode(i);
        		if(!(keyss.indexOf(key2)+1))keyss.push(key2);
        		for(let i2='0'.charCodeAt(0);i2<='9'.charCodeAt(0);i2++){
        			let key2=String.fromCharCode(i)+String.fromCharCode(i2);
        			if(!(keyss.indexOf(key2)+1))keyss.push(key2);
        			for(let i3='0'.charCodeAt(0);i3<='9'.charCodeAt(0);i3++){
        				let key2=String.fromCharCode(i)+String.fromCharCode(i2)+String.fromCharCode(i3);
        				if(!(keyss.indexOf(key2)+1))keyss.push(key2);
        			}
        			for(let i3='a'.charCodeAt(0);i3<='z'.charCodeAt(0);i3++){
        				let key2=String.fromCharCode(i)+String.fromCharCode(i2)+String.fromCharCode(i3);
        				if(!(keyss.indexOf(key2)+1))keyss.push(key2);
        			}
        			for(let i3='A'.charCodeAt(0);i3<='Z'.charCodeAt(0);i3++){
        				let key2=String.fromCharCode(i)+String.fromCharCode(i2)+String.fromCharCode(i3);
        				if(!(keyss.indexOf(key2)+1))keyss.push(key2);
        			}
        		}
        		
        		for(let i2='a'.charCodeAt(0);i2<='z'.charCodeAt(0);i2++){
        			let key2=String.fromCharCode(i)+String.fromCharCode(i2);
        			if(!(keyss.indexOf(key2)+1))keyss.push(key2);
        			for(let i3='0'.charCodeAt(0);i3<='9'.charCodeAt(0);i3++){
        				let key2=String.fromCharCode(i)+String.fromCharCode(i2)+String.fromCharCode(i3);
        				if(!(keyss.indexOf(key2)+1))keyss.push(key2);
        			}
        			for(let i3='a'.charCodeAt(0);i3<='z'.charCodeAt(0);i3++){
        				let key2=String.fromCharCode(i)+String.fromCharCode(i2)+String.fromCharCode(i3);
        				if(!(keyss.indexOf(key2)+1))keyss.push(key2);
        			}
        			for(let i3='A'.charCodeAt(0);i3<='Z'.charCodeAt(0);i3++){
        				let key2=String.fromCharCode(i)+String.fromCharCode(i2)+String.fromCharCode(i3);
        				if(!(keyss.indexOf(key2)+1))keyss.push(key2);
        			}
        		}
        		
        		for(let i2='A'.charCodeAt(0);i2<='Z'.charCodeAt(0);i2++){
        			let key2=String.fromCharCode(i)+String.fromCharCode(i2);
        			if(!(keyss.indexOf(key2)+1))keyss.push(key2);
        			for(let i3='0'.charCodeAt(0);i3<='9'.charCodeAt(0);i3++){
        				let key2=String.fromCharCode(i)+String.fromCharCode(i2)+String.fromCharCode(i3);
        				if(!(keyss.indexOf(key2)+1))keyss.push(key2);
        			}
        			for(let i3='a'.charCodeAt(0);i3<='z'.charCodeAt(0);i3++){
        				let key2=String.fromCharCode(i)+String.fromCharCode(i2)+String.fromCharCode(i3);
        				if(!(keyss.indexOf(key2)+1))keyss.push(key2);
        			}
        			for(let i3='A'.charCodeAt(0);i3<='Z'.charCodeAt(0);i3++){
        				let key2=String.fromCharCode(i)+String.fromCharCode(i2)+String.fromCharCode(i3);
        				if(!(keyss.indexOf(key2)+1))keyss.push(key2);
        			}
        		}
            }
        break;
		default:
			was=false;
		break;
	}
	stageBF++;
	if(was){
		WorkerTimer.setTimeout(function(){init_BF(msg);},0);
	}else{
		BFin=true;
		TTD(msg);
	}
}
function clearr(){
	document.getElementById('possibles').innerHTML='<span>возможные варианты:</span><br><input type="button" value="Очистить" onclick="clearr();">';
	document.getElementById('possibles').style.display='none';
}
document.getElementById('actDec').onclick=function(){
	let key=document.getElementById('key').value;
	document.getElementById('resDec').value='';
	
	let msg=document.getElementById('dec').value.toUpperCase().match(/^.{0,}(AP ID OG|PP|VK CO FF EE|VK C0 FF EE|II) ([A-F0-9\s]+) (AP ID OG|PP|VK CO FF EE|VK C0 FF EE|II).{0,}$/);
	let tempDec=[123];
	if(msg!=null){
		document.getElementById('dec').value=msg[1]+' '+msg[2]+' '+msg[3];
		tempDec=dec2(msg[1]+' '+msg[2]+' '+msg[3],key)[0];
	}
	if(tempDec[0]===null){
		document.getElementById('resDec').style.color='#F00';
		document.getElementById('resDec').value="<Нужен ключ>";
		WorkerTimer.setTimeout(function(){document.getElementById('resDec').style.color='';},2e3);
		if(document.getElementById('possibles')&&tempDec[1].match(/а-яА-Яa-zA-Z0-9/)){
			let kek=document.getElementById('possibles');
			kek.style.display='block';
			let kekin=document.createElement('input');
			kekin.value=tempDec[1];
			kek.appendChild(kekin);
		}
		
	}else if(tempDec[0]==123){
		document.getElementById('resDec').style.color='#F00';
		document.getElementById('resDec').value='<Ошибка в шифре>';
		WorkerTimer.setTimeout(function(){document.getElementById('resDec').style.color='';},2e3);
	}else{
		document.getElementById('resDec').style.color='#0F0';
		document.getElementById('resDec').value=tempDec;
		WorkerTimer.setTimeout(function(){document.getElementById('resDec').style.color='';},5e2);
	}
};
document.getElementById('actEnc').onclick=function(){
	let key=document.getElementById('key').value;
	
	document.getElementById('resEnc').style.color='#0F0';
	document.getElementById('resEnc').value=enc(document.getElementById('enc').value,key);
	WorkerTimer.setTimeout(function(){document.getElementById('resEnc').style.color='';},5e2);
};
var gi=0;
var keyss=[];
document.getElementById('act2').onclick=function(){
	document.getElementById('resDec').value='';
	let msg=document.getElementById('dec').value.toUpperCase().match(/^.{0,}(AP ID OG|PP|VK CO FF EE|VK C0 FF EE|II) ([A-F0-9\s]+) (AP ID OG|PP|VK CO FF EE|VK C0 FF EE|II).{0,}$/);
	if(msg!=null)TTD(msg[1]+' '+msg[2]+' '+msg[3]);
}

function getWords1(){
    let t1=[
		"omegakek",
		"kjk",
		"lel",
		"pidr",
		"лел",
		"жока",
		"бока",
		"жека",
		"инжир",
		"инжыр",
		"сук",
		"cerf",
		"lie",
		"vkcoffee",
		"VK CO FF EE",
		"VK C0 FF EE",
		"VKCOFFEE",
		"кофе",
        "monkey",
        "12345",
        "123",
        "starwars",
        "112233",
        "666666",
        "0000",
        "4321",
        "1111",
        "123654",
        "soccer",
        "whatever",
        "hello",
        "dragon",
        "hacker",
        "master",
        "121212",
        "102030",
        "00000000",
        "test",
        "00000",
        "computer",
        "147852",
        "hunter",
        "sunshine",
        "0123456",
        "summer",
        "qwertz",
        "fuckyou",
        "87654321",
        "swordfish",
        "11111111",
        "freedom",
        "diablo",
        "startrek",
        "333333",
        "xxxxxx",
        "asdf",
        "11223344",
        "4444",
        "000",
        "test123",
        "ssssss",
        "sparky",
        "777777",
        "11111",
        "hahaha",
        "456456",
        "spider",
        "gamer",
        "warrior",
        "1212",
        "trustno1",
        "sucker",
        "qwertyui",
        "nintendo",
        "killer",
        "mike",
        "hitman",
        "google",
        "westside",
        "vegeta",
        "qwert",
        "741852",
        "wolverine",
        "medion",
        "halflife",
        "777",
        "456789",
        "fucker",
        "8888",
        "444444",
        "123465",
        "testtest",
        "tennis",
        "qwer",
        "qwe",
        "mohamed",
        "starcraft",
        "matthew",
        "0000000",
        "yellow",
        "moomoo",
        "monster",
        "merlin",
        "gateway",
        "secret",
        "redalert",
        "pass",
        "hockey",
        "gundam",
        "cheese",
        "banana",
        "warcraft3",
        "ultima",
        "mohammed",
        "sanane",
        "ghost",
        "qwertyuiop",
        "wutang",
        "testing",
        "mickey",
        "heroes",
        "golden",
        "combat18",
        "778899",
        "1980",
        "azerty",
        "gangster",
        "asdfasdf",
        "789654",
        "motorola",
        "megaman",
        "hammer",
        "shadow",
        "qazqaz",
        "manutd",
        "456123",
        "1122",
        "010101",
        "wert",
        "voyager",
        "something",
        "sniper",
        "skater",
        "nemesis",
        "mnbvcxz",
        "kkkkkk",
        "infinity",
        "geheim",
        "digital",
        "202020",
        "windows",
        "111222",
        "scooter",
        "753951",
        "united",
        "stupid",
        "snake",
        "mememe",
        "iceman",
        "freeman",
        "fireball",
        "westlife",
        "warcraft",
        "siemens",
        "sakura",
        "qaz123",
        "nothing",
        "iloveyou",
        "homer",
        "gizmo",
        "georgia",
        "galaxy",
        "7777",
        "stargate",
        "jordan",
        "wassup",
        "tiger",
        "spencer",
        "snickers",
        "raptor",
        "online",
        "moocow",
        "montana",
        "makaveli",
        "idontknow",
        "hotdog",
        "greenday",
        "friends",
        "basketball",
        "asdasd",
        "741852963",
        "5555",
        "333",
        "1987",
        "simpsons",
        "dennis",
        "asd123",
        "123654789",
        "surfer",
        "sultan",
        "sssss",
        "sputnik",
        "spitfire",
        "silver",
        "lollol",
        "legend",
        "darkness",
        "arsenal",
        "852456",
        "1988",
        "19851985",
        "012345",
        "yankees",
        "thuglife",
        "tester",
        "super",
        "skyline",
        "mehmet",
        "legolas",
        "kokoko",
        "kitty",
        "king",
        "iamgod",
        "green",
        "gogogo",
        "ghetto",
        "free",
        "888",
        "jackson",
        "chicken",
        "3333",
        "147147",
        "0000000000",
        "qwerty123",
        "lol123",
        "2222",
        "1111111",
        "winter",
        "willow",
        "webmaster",
        "toyota",
        "tomcat",
        "terminator",
        "tekken",
        "system",
        "sweety",
        "sunset",
        "stella",
        "spike",
        "spears",
        "sonic",
        "someone",
        "slayer",
        "qazwsxedc",
        "motherfucker",
        "mario",
        "isabelle",
        "insane",
        "helpme",
        "hassan",
        "hannibal",
        "frankie",
        "france",
        "counter",
        "celtic",
        "asd",
        "789456123",
        "445566",
        "19871987",
        "142536",
        "007007",
        "212121",
        "1985",
        "14531453",
        "123789",
        "theone",
        "qazxsw",
        "ninja",
        "letmein",
        "jimmy",
        "hehehe",
        "forever",
        "020202",
        "winner",
        "williams",
        "wasser",
        "vietnam",
        "terror",
        "taurus",
        "sydney",
        "soso",
        "qwerasdf",
        "morpheus",
        "monika",
        "money",
        "miller",
        "mephisto",
        "meister",
        "kingkong",
        "killbill",
        "karate",
        "ismail",
        "ihateyou",
        "honda",
        "frozen",
        "fishing",
        "firebird",
        "compaq",
        "westwood",
        "werder",
        "voodoo",
        "therock",
        "subaru",
        "student",
        "stinger",
        "sports",
        "speed",
        "spartak",
        "simone",
        "rocky",
        "people",
        "nigger",
        "manson",
        "leonardo",
        "germany",
        "garbage",
        "ficken",
        "blahblah",
        "batman",
        "asshole",
        "8675309",
        "1986",
        "007",
        "immortal",
        "hardcore",
        "diesel",
        "252525",
        "zxcv",
        "xavier",
        "wwwwww",
        "wordpass",
        "victor",
        "veronica",
        "undead",
        "tottenham",
        "tornado",
        "stonecold",
        "start",
        "squall",
        "ronaldo",
        "rangers",
        "monalisa",
        "megadeth",
        "marcus",
        "jessie",
        "hollywood",
        "hamada",
        "golfergames",
        "galatasaray",
        "fuckme",
        "1990",
        "19891989",
        "19861986",
        "134679",
        "0523213511",
        "kawasaki",
        "falcon",
        "141414",
        "123987",
        "yamaha",
        "yahoo",
        "werwer",
        "sunny",
        "stardust",
        "sss",
        "speedy",
        "sommer",
        "soldier",
        "school",
        "savage",
        "psycho",
        "passme",
        "none",
        "ncc1701",
        "mustafa",
        "kickass",
        "khalid",
        "jeremy",
        "istanbul",
        "gggggg",
        "gfhjkm",
        "741741",
        "369852",
        "19841984",
        "19831983",
        "wizard",
        "wilson",
        "wicked",
        "water",
        "vivian",
        "unreal",
        "turtle",
        "tomtom",
        "thumper",
        "thebest",
        "storm",
        "snowball",
        "skywalker",
        "qwerty1",
        "prince",
        "passwort",
        "mortal",
        "moon",
        "megan",
        "maverick",
        "kitten",
        "kissmyass",
        "ireland",
        "inside",
        "indiana",
        "ibanez",
        "hobbit",
        "hhhhhh",
        "groovy",
        "gotohell",
        "fluffy",
        "finalfantasy",
        "fighter",
        "124578",
        "123456a",
        "1010",
        "zxcvb",
        "zxc123",
        "zidane",
        "yoyoyo",
        "winston",
        "william",
        "striker",
        "scorpion",
        "scarface",
        "samurai",
        "pepsi",
        "pantera",
        "omega",
        "november",
        "nopass",
        "nelson",
        "natalie",
        "michael",
        "mama",
        "logitech",
        "koko",
        "jack",
        "gandalf",
        "ferrari",
        "creative",
        "besiktas",
        "bambam",
        "andrea",
        "7895123",
        "7654321",
        "454545",
        "1984",
        "115599",
        "000123",
        "stefan",
        "passw0rd",
        "gothic",
        "beckham",
        "xxxxx",
        "winnie",
        "west",
        "werner",
        "welcome",
        "weasel",
        "unknown",
        "tweety",
        "travis",
        "thegame",
        "target",
        "suzuki",
        "superman1",
        "suckit",
        "strawberry",
        "stephen",
        "stanley",
        "spooky",
        "spidey",
        "solomon",
        "solaris",
        "smallville",
        "singapore",
        "samantha",
        "rainbow",
        "raiders",
        "rabbit",
        "power",
        "oooooo",
        "myself",
        "mouse",
        "moose",
        "moonlight",
        "mirage",
        "millenium",
        "michael1",
        "melisa",
        "megatron",
        "marlboro",
        "kenshin",
        "kamikaze",
        "jasmin",
        "inferno",
        "iloveme",
        "iddqd",
        "hellsing",
        "guardian",
        "goodluck",
        "gangsta",
        "gameover",
        "fuck",
        "friday",
        "freddy",
        "freddie",
        "forum",
        "flatron",
        "fender",
        "fantasy",
        "deadman",
        "asdfg",
        "andrew",
        "555",
        "369369",
        "336699",
        "19881988",
        "19761976",
        "000111",
        "warhammer",
        "undertaker",
        "mmmmmm",
        "matrix",
        "harley",
        "donkey",
        "blabla",
        "barney",
        "321654",
        "1977",
        "123000",
        "12121212",
        "zxczxc",
        "topgun",
        "thunder",
        "spiderman",
        "rocket",
        "remember",
        "qqqqq",
        "qqqq",
        "predator",
        "perfect",
        "pascal",
        "parola",
        "myname",
        "manowar",
        "kungfu",
        "himmler",
        "guitar",
        "fred",
        "charmed",
        "blade",
        "bbbbbb",
        "avatar",
        "55555555",
        "456654",
        "321",
        "2000",
        "19801980",
        "19781978",
        "19731973",
        "191919",
        "13579",
        " 01230123",
        "77777",
        "54321",
        "qwert ",
        "22222",
        "555555",
        "33333",
        "99999",
        "88888",
        "66666",
        "1234567890",
        "ghbdtn",
        "princess",
        "rockyou",
        "abc123",
        "nicole",
        "daniel",
        "babygirl",
        "jessica",
        "LOVELY",
        "ashley",
        "iloveu",
        "michelle",
        "tigger",
        "password1",
        "chocolate",
        "anthony",
        "angel",
        "butterfly",
        "purple",
        "liverpool",
        "justin",
        "loveme",
        "football",
        "carlos",
        "jennifer",
        "joshua",
        "superman",
        "bubbles",
        "hannah",
        "amanda",
        "loveyou",
        "pretty",
        "angels",
        "flower",
        "elizabeth",
        "PLAYBOY",
        "TINKERBELL",
        "jasmine",
        "charlie",
        "brandon",
        "hottie",
        "chelsea",
        "teamo",
        "barbie",
        "lovers",
        "melissa",
        "danielle",
        "robert",
        "EMINEM",
        "family",
        "JONATHAN",
        "vanessa",
        "cookie",
        "spongebob",
        "junior",
        "joseph",
        "taylor",
        "lauren",
        "daniela",
        "jesus",
        "princesa",
        "softball",
        "alexis",
        "alexandra",
        "miguel",
        "estrella",
        "thomas",
        "patrick",
        "angela",
        "beautiful",
        "poohbear",
        "mylove",
        "adrian",
        "alexander",
        "america",
        "destiny",
        "christian",
        "princess1",
        "richard",
        "monica",
        "diamond",
        "sayang",
        "dancer",
        "carolina",
        "steven",
        "louise",
        "shorty",
        "nathan",
        "gabriel",
        "snoopy",
        "orange",
        "alejandro",
        "SANDRA",
        "brittany",
        "cherry",
        "alejandra",
        "buster",
        "george",
        "patricia",
        "rachel",
        "antonio",
        "david",
        "tequiero",
        "heather",
        "FERNANDO",
        "STEPHANIE",
        "victoria",
        "dolphin",
        "ginger",
        "blink182",
        "manuel",
        "peanut",
        "beauty",
        "corazon",
        "angel1",
        "sweetie",
        "honey",
        "cristina",
        "pokemon",
        "ricardo",
        "maggie",
        "rebelde",
        "kisses",
        "babygurl",
        "pepper",
        "myspace",
        "martin",
        "heaven",
        "alyssa",
        "baseball",
        "madison",
        "123abc",
        "mother",
        "morgan",
        "maria",
        "mariposa",
        "december",
        "gabriela",
        "september",
        "55555",
        "bailey",
        "iloveyou2",
        "shannon",
        "mahalkita",
        "kimberly",
        "pamela",
        "babygirl1",
        "gemini",
        "tiffany",
        "pictures",
        "claudia",
        "angelica",
        "sophie",
        "hellokitty",
        "andres",
        "inuyasha",
        "austin",
        "eduardo",
        "mariana",
        "courtney",
        "chris",
        "JESUS1",
        "booboo",
        "horses",
        "iloveyou1",
        "precious",
        "mahalko",
        "october",
        "adriana",
        "peaches",
        "kissme",
        "james",
        "cutie",
        "diana",
        "crystal",
        "edward",
        "jackie",
        "christopher",
        "sebastian",
        "oliver",
        "KARINA",
        "friend",
        "kenneth",
        "johnny",
        "rebecca",
        "samsung",
        "scooby",
        "angelo",
        "CARMEN",
        "888888",
        "hotmail",
        "barcelona",
        "orlando",
        "bitch",
        "cameron",
        "samuel",
        "brenda",
        "august",
        "50cent",
        "kevin",
        "monkey1",
        "bonita",
        "isabel",
        "karen",
        "babyboy",
        "cutiepie",
        "casper",
        "javier",
        "mustang",
        "0123456789",
        "bowwow",
        "maganda",
        "laura",
        "sarah",
        "denise",
        "portugal",
        "chrisbrown",
        "nicholas",
        "alicia",
        "marvin",
        "jasper",
        "cuteako",
        "cristian",
        "bianca",
        "rockstar",
        "JANUARY",
        "tigers",
        "smokey",
        "chester",
        "flowers",
        "fuckoff",
        "love123",
        "benfica",
        "volleyball",
        "INTERNET",
        "tintin",
        "garfield",
        "sweet",
        "jordan23",
        "cassie",
        "Francis",
        "aaliyah",
        "harrypotter",
        "monique",
        "camila",
        "charles",
        "panget",
        "olivia",
        "cancer",
        "101010",
        "Brianna",
        "vincent",
        "midnight",
        "lollipop",
        "lorena",
        "superstar",
        "mexico",
        "christine",
        "rafael",
        "abigail",
        "katherine",
        "scorpio",
        "nirvana",
        "MERCEDES",
        "696969",
        "benjamin",
        "apples",
        "POOKIE",
        "johncena",
        "BROOKE",
        "abcdef",
        "sergio",
        "icecream",
        "andreea",
        "julian",
        "METALLICA",
        "hiphop",
        "dakota",
        "fernanda",
        "sabrina",
        "lovelove",
        "mybaby",
        "jeffrey",
        "roberto",
        "catherine",
        "babyblue",
        "melanie",
        "badboy",
        "dolphins",
        "sasuke",
        "blondie",
        "smiley",
        "teresa",
        "jason",
        "simple",
        "raymond",
        "ronald",
        "anthony1",
        "newyork",
        "santiago",
        "steaua",
        "minnie",
        "gatita",
        "JEROME",
        "chivas",
        "nicole1",
        "PIGLET",
        "asdfghjkl",
        "valeria",
        "alberto",
        "bitch1",
        "slideshow",
        "chris1",
        "jayson",
        "leslie",
        "muffin",
        "christ",
        "liliana",
        "BROOKLYN",
        "jayjay",
        "jenny",
        "lover",
        "amores",
        "ladybug",
        "sweetheart",
        "gandako",
        "sexygirl",
        "cookies",
        "dexter",
        "popcorn",
        "miamor",
        "babyko",
        "fatima",
        "babydoll",
        "rockon",
        "5201314",
        "colombia",
        "eeyore",
        "246810",
        "christina",
        "single",
        "tatiana",
        "happy",
        "skittles",
        "britney",
        "lakers",
        "albert",
        "teddybear",
        "12345678910",
        "linda",
        "london",
        "lalala",
        "katrina",
        "francisco",
        "natalia",
        "charlotte",
        "marie",
        "angelito",
        "mahal",
        "grace",
        "amorcito",
        "cocacola",
        "paola",
        "pasaway",
        "mommy1",
        "cantik",
        "manchester",
        "159357",
        "genesis",
        "kelsey",
        "amigos",
        "shelby",
        "brandy",
        "garcia",
        "teiubesc",
        "linkinpark",
        "diego",
        "fuckyou1",
        "1234567",
        "000000",
        "qwerty",
        "1234",
        "qazwsx",
        "1q2w3e",
        "123qwe",
        "123123123",
        "qwe123",
        "1q2w3e4r",
        "987654321",
        "9379992",
        "qweqwe",
        "q1w2e3r4",
        "999999999",
        "1qaz2wsx",
        "111",
        "qqqqqq",
        "789456",
        "qwaszx",
        "666",
        "aaaaaa",
        "147852369",
        "123454321",
        "555666",
        "321321",
        "123qweasd",
        "12341234",
        "0987654321",
        "123456qwerty",
        "qwerty123456",
        "1q2w3e4r5t6y",
        "y6t5r4e3w2q1",
        "6y5t4r3e2w1q",
        "09876ytrewq",
        "67890qwerty",
        "qwerty666",
        "666qwerty",
        "qwertyqwerty",
        "q6w5e4r3t2y1",
        "cdexswzaq",
        "qwertyasdfgh",
        "q1q2q3q4q5q6",
        "zzzzzz",
        "zerocool",
        "god",
        "love",
        "sex",
        "porn",
        "smile",
        "admin",
        "user",
        "guest",
        "root",
        "cool",
        "unlock",
        "lol",
        "lamer",
        "best",
        "intel",
        "abcd",
        "funny",
        "move",
        "maximius",
        "111111",
        "123456789",
        "q1w2e3",
        "k.,jdm",
        "nokia",
        "star",
        "stalker",
        "myspace1",
        "baseball1",
        "football1",
        "slipknot",
        "123456",
        "123321",
        "7777777",
        "12345678",
        "пароль",
        "123123",
        "йцукен",
        "zxcvbnm",
        "любовь",
        "654321",
        "zxcvbn",
        "159753",
        "1q2w3e4r5t",
        "привет",
        "4815162342",
        "qweasdzxc",
        "knopka",
        "vkontakte",
        "asdfgh",
        "password",
        "qwertyu",
        "fyfcnfcbz",
        "cjkysirj",
        "солнышко",
        "131313",
        "анастасия",
        "qweasd",
        "fylhtq",
        "nastya",
        "genius",
        "какашка",
        "андрей",
        "любимый",
        "fktrcfylh",
        "rfrfirf",
        "александр",
        "максим",
        "12344321",
        "vfhbyf",
        "marina",
        "natasha",
        "zxcvbnm,.",
        "наташа",
        "999999",
        "nikita",
        "hjvfirf",
        "ятебялюблю",
        "1234qwer",
        "222222",
        "кристина",
        "adidas",
        "88888888",
        "1й2ц3у",
        "dfvgbh",
        "serega",
        "малышка",
        "k.,bvsq",
        "люблюего",
        "q1w2e3r4t5",
        "йцукенгшщзхъ",
        "ячсмит",
        "rhbcnbyf",
        "maksim",
        "fktrctq",
        "мамочка",
        "вконтакте",
        "yfnfif",
        "марина",
        "любимая",
        "135790",
        "gbpltw",
        "666999",
        "vfvjxrf",
        "люблютебя",
        "dbrnjhbz",
        "ghbdtnbr",
        "trfnthbyf",
        "cjkywt",
        "znt,zk.,k.",
        "vfksirf",
        "147258369",
        "andrey",
        "hesoyam",
        "987654",
        "147258",
        "kotenok",
        "cxfcnmt",
        "kirill",
        "kontakt",
        "виктория",
        "microlab",
        "polina",
        "kristina",
        "1й2ц3у4к",
        "ненавижу",
        "drjynfrnt",
        "naruto",
        "1234554321",
        "k.,bvfz",
        "ялюблютебя",
        "контакт",
        "q1w2e3r4t5y6",
        "rjynfrn",
        "я тебя люблю",
        "rammstein",
        "qwer1234",
        "алексей",
        "дмитрий",
        "adgjmptw",
        "ромашка",
        "russia",
        "леночка",
        "19921992",
        "rjntyjr",
        "yjdsqgfhjkm",
        "1q2w3e4r5t6y7u8i9  o0p",
        "010203",
        "1029384756",
        "rambler",
        "lvbnhbq",
        "kakashka",
        "232323",
        "женечка",
        "pizdec",
        "1111111111",
        "19911991",
        "rfnthbyf",
        "zk.,k.nt,z",
        "никита",
        "vfrcbvrf",
        "екатерина",
        "123456q",
        "zk.,k.ct,z",
        "ялюблюсебя",
        "defender",
        "porsche",
        "rosebud",
        "butter",
        "beach",
        "jaguar",
        "amateur",
        "great",
        "black",
        "pussy",
        "steelers",
        "cooper",
        "nascar",
        "redsox",
        "1313",
        "mountain",
        "golf",
        "bond007",
        "murphy",
        "bear",
        "frank",
        "brazil",
        "xxxxxxxx",
        "doctor",
        "dave",
        "japan",
        "eagle1",
        "naked",
        "phoenix",
        "gators",
        "squirt",
        "stars",
        "apple",
        "knight",
        "thx1138",
        "porno",
        "steve",
        "aaaa",
        "bonnie",
        "6969",
        "debbie",
        "viper",
        "horny",
        "ou812",
        "ranger",
        "booger",
        "jake",
        "matt",
        "iwantu",
        "player",
        "flyers",
        "fish",
        "gregory",
        "beaver",
        "buddy",
        "4128",
        "boomer",
        "teens",
        "young",
        "runner",
        "cowboys",
        "swimming",
        "lucky",
        "walter",
        "gordon",
        "girls",
        "cumshot",
        "boston",
        "access",
        "coffee",
        "braves",
        "shit",
        "yankee",
        "college",
        "saturn",
        "bulldog",
        "baby",
        "cunt",
        "brian",
        "tucker",
        "mark",
        "john",
        "canada",
        "mercedes",
        "sierra",
        "blazer",
        "sexy",
        "5150",
        "leather",
        "cumming",
        "spanky",
        "doggie",
        "hunting",
        "gunner",
        "beavis",
        "horney",
        "bigcock",
        "bubba",
        "arthur",
        "dallas",
        "2112",
        "cream",
        "ladies",
        "calvin",
        "panties",
        "johnson",
        "naughty",
        "shaved",
        "giants",
        "tits",
        "booty",
        "samson",
        "member",
        "blonde",
        "kelly",
        "blowme",
        "boobs",
        "fucked",
        "paul",
        "donald",
        "mine",
        "golfer",
        "bigdaddy",
        "0",
        "bronco",
        "fire",
        "racing",
        "penis",
        "sandra",
        "chicago",
        "pookie",
        "eagle",
        "packers",
        "hentai",
        "birdie",
        "einstein",
        "sexsex",
        "trouble",
        "little",
        "biteme",
        "white",
        "redwings",
        "enter",
        "chevy",
        "smith",
        "willie",
        "bigtits",
        "sticky",
        "bitches",
        "cowboy",
        "sammy",
        "animal",
        "panther",
        "slut",
        "broncos",
        "private",
        "magic",
        "skippy",
        "nipples",
        "driver",
        "blondes",
        "marine",
        "enjoy",
        "corvette",
        "scott",
        "girl",
        "bigdog",
        "vagina",
        "apollo",
        "parker",
        "maddog",
        "video",
        "hooters",
        "time",
        "paris",
        "butthead",
        "rock",
        "women",
        "srinivas",
        "xxxx",
        "fucking",
        "internet",
        "extreme",
        "magnum",
        "blowjob",
        "captain",
        "action",
        "redskins",
        "juice",
        "bigdick",
        "carter",
        "erotic",
        "abgrtyu",
        "dirty",
        "ford",
        "dreams",
        "camaro",
        "maxwell",
        "music",
        "dick",
        "viking",
        "access14",
        "rush2112",
        "bill",
        "wolf",
        "blue",
        "nipple",
        "eagles",
        "peter",
        "pussies",
        "alex",
        "cock",
        "florida",
        "mistress",
        "house",
        "beer",
        "eric",
        "phantom",
        "billy",
        "theman",
        "movie",
        "6666",
        "please",
        "success",
        "metallica",
        "eminem",
        "golfer29",
        "games",
        "karina",
        "01230123",
        "joycasino",
        "joycasino1",
        "animevost",
        "animevost.org",
        "dadada",
        "adadad",
        "google.com",
        "vk.com",
        "1",
        "22222222",
        "5555555",
        "9876543",
        "qaz",
        "77777777",
        "consult",
        "98765432",
        "33333333",
        "3333333",
        "2345678",
        "2222222",
        "12345Ab",
        "99999999",
        "9999999",
        "23456789",
        "8888888",
        "12345678909",
        "123456789098",
        "1234567890987",
        "12345678909876",
        "123456789098765",
        "1234567890987654",
        "12345678909876543",
        "123456789098765432",
        "1234567890987654321",
        "00",
        "01",
        "0123",
        "01234",
        "0123456789abcdef",
        "10",
        "100",
        "1000",
        "10000",
        "100000",
        "1000000",
        "10000001",
        "1000001",
        "100001",
        "10001",
        "1001",
        "101",
        "11",
        "12",
        "121",
        "1221",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "1xbet",
        "2",
        "20",
        "21",
        "22",
        "222",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "3",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "4",
        "40",
        "41",
        "42",
        "43",
        "432",
        "44",
        "444",
        "45",
        "46",
        "47",
        "48",
        "49",
        "5",
        "50",
        "54",
        "543",
        "5432",
        "55",
        "56",
        "6",
        "65",
        "654",
        "6543",
        "65432",
        "66",
        "7",
        "76",
        "765",
        "7654",
        "76543",
        "765432",
        "77",
        "77564898",
        "8",
        "87",
        "876",
        "8765",
        "87654",
        "876543",
        "8765432",
        "88",
        "9",
        "98",
        "987",
        "9876",
        "98765",
        "9876543210",
        "98765432100123456789",
        "9876543210123456789",
        "987654321123456789",
        "98765432123456789",
        "9876543223456789",
        "987654323456789",
        "98765433456789",
        "9876543456789",
        "987654456789",
        "98765456789",
        "9876556789",
        "987656789",
        "98766789",
        "9876789",
        "987789",
        "98789",
        "9889",
        "989",
        "99",
        "999",
        " ",
        "  ",
        "   ",
        "    ",
        "     ",
        "!",
        "#",
        "$",
        "%",
        "&",
        "*",
        "-",
        "/",
        "//",
        ":",
        "=",
        "?",
        "@",
        "^",
        "_",
        "a",
        "ah",
        "aha",
        "ahah",
        "ahaha",
        "ahahah",
        "ab",
        "abc",
        "abc1",
        "abc12",
        "abc1234",
        "abc12345",
        "abc123456",
        "abc321",
        "abcabc",
        "abcba",
        "abccba",
        "abcde",
        "abcdefg",
        "afk",
        "and",
        "ass",
        "b",
        "bad",
        "ban",
        "bcd",
        "block",
        "bonk",
        "boy",
        "c",
        "ca",
        "cat",
        "cb",
        "cba",
        "cba123",
        "cba321",
        "chaz",
        "cheat",
        "check",
        "chrome",
        "cover",
        "d",
        "da",
        "dac",
        "dack",
        "dfdfdf",
        "dog",
        "duck",
        "dratuty",
        "Dratuty",
        "e",
        "err",
        "error",
        "f",
        "fail",
        "false",
        "file",
        "g",
        "go",
        "game",
        "good",
        "h",
        "ha",
        "hah",
        "haha",
        "hahah",
        "hack",
        "hacked",
        "he",
        "heh",
        "hehe",
        "heheh",
        "here",
        "hi",
        "hole",
        "holy",
        "host",
        "i",
        "io",
        "I",
        "j",
        "joke",
        "k",
        "kek",
        "kick",
        "kill",
        "l",
        "m",
        "main",
        "man",
        "max",
        "mom",
        "n",
        "name",
        "new",
        "no",
        "noob",
        "nope",
        "o",
        "of",
        "off",
        "offline",
        "on",
        "one",
        "out",
        "p",
        "pa",
        "pas",
        "passw",
        "passwo",
        "passwor",
        "pen",
        "pi",
        "pidor",
        "pro",
        "q",
        "qw",
        "r",
        "rar",
        "room",
        "s",
        "SL",
        "SL21",
        "t",
        "true",
        "two",
        "u",
        "v",
        "w",
        "wasd",
        "win",
        "wow",
        "x",
        "xd",
        "xyz",
        "xyz123",
        "y",
        "yea",
        "yeah",
        "yes",
        "yup",
        "z",
        "~",
        "      ",
        "1q2w3e4r5t6y7u8i9o0p",
        "amatory",
        "098765",
        "tdutybq",
        "ybrbnf",
        "natali",
        "идинахуй",
        "котенок",
        "deniska",
        "сашенька",
        "nfnmzyf",
        "sergey",
        "lokomotiv",
        "12345qwert",
        "romashka",
        "приветик",
        "ruslan",
        "aleksandr",
        "sobaka",
        "artemka",
        "159951",
        "максимка",
        "люблю тебя",
        "aspirine",
        "19931993",
        "19941994",
        "rbhbkk",
        "я люблю тебя",
        "vfvekz",
        "aezakmi",
        "123йцу",
        "люблюсебя",
        "privet",
        "ktyjxrf",
        "alexandr",
        "nuttertools",
        "fytxrf",
        "cfitymrf",
        "1qaz2wsx3edc",
        "anastasia",
        "oksana",
        "dkflbvbh",
        "ячсмитьбю.",
        "солнце",
        "ghjcnj",
        "александра",
        "fktrcfylhf",
        "анютка",
        "1123581321",
        "мамуля",
        "1qazxsw2",
        "veronika",
        "pupsik",
        "вероника",
        "sonyericsson",
        "moloko",
        "951753",
        "красотка",
        "катерина",
        "телефон",
        "rhfcjnrf",
        "кнопка",
        "счастье",
        "blbyf",
        "eq",
        "panasonic",
        "maximus",
        "kolobok",
        "qawsed",
        "дениска",
        "сергей",
        "nokian73",
        "маруся",
        "katerina",
        "ячсмить",
        "ryjgrf",
        "вампир",
        "asdfghj",
        "11235813",
        "zaqwsx",
        "valera",
        "gegcbr",
        "qazwsxedcrfv",
        "solnce",
        "cthutq",
        "asdzxc",
        "йфяцыч",
        "ytyfdb",
        "vfczyz",
        "cdtnkfyf",
        "димочка",
        "валера",
        "1478963",
        "ltybcrf",
        "vfhecz",
        "5555555555",
        "кирилл",
        "ytrewq",
        "nokia6233",
        "svetlana",
        "татьяна",
        "иришка",
        "258456",
        "nokia6300",
        "пиздец",
        "катюшка",
        "vladimir",
        "пупсик",
        "parkour",
        "новыйпароль",
        "qwerty12",
        "alenka",
        "маргарита",
        "rfhbyf",
        "йцукенгшщз",
        "vitalik",
        "полина",
        "1й2ц3у4к5е",
        "спартак",
        "12369874",
        "25802580",
        "fy.nrf",
        "102938",
        "9293709b13",
        "1a2b3c",
        "906090",
        "assassin",
        "jktymrf",
        "ntktajy",
        "ekaterina",
        "rfrnec",
        "ялюблю",
        "евгений",
        "1234321",
        "mazafaka",
        "йцукенг",
        "QWERTY",
        "456852",
        "qwerty12345",
        "настенька",
        "666777",
        "20082008",
        "philips",
        "qazxswedc",
        "123456789q",
        "svetik",
        "zaqxsw",
        "1366613",
        "катюша",
        "анечка",
        "19901990",
        "масяня",
        "rfn.if",
        "оленька",
        "ксения",
        "k.,k.ct,z",
        "лапочка",
        "73501505",
        "vladik",
        "rereirf",
        "bhbirf",
        "vfvfgfgf",
        "фывапр",
        "яяяяяя",
        "twilight",
        "yandex",
        "yfcntymrf",
        "йфяцычувс",
        "121314",
        "pft,fkb",
        "sashka",
        "шоколад",
        "192837465",
        "vbkfirf",
        "кактус",
        "123098",
        "k.,k.nt,z",
        "фывапролджэ",
        "светик",
        "qwerasdfzxcv",
        "михаил",
        "moscow",
        "светлана",
        "cnthdf",
        "19951995",
        "dkflbckfd",
        "ybrjkfq",
        "dfkthbz",
        "alinka",
        "fgtkmcby",
        "lost4815162342",
        "dialog",
        "kfgjxrf",
        "1234512345",
        "антошка",
        "милашка",
        "nikitos",
        "jrcfyf",
        "владимир",
        "fyutkjxtr",
        "loveless",
        "motherlode",
        "cvthnm",
        "zaq123",
        "руслан",
        "sterva",
        "krasotka",
        "rfn.irf",
        "sergei",
        "lbvjxrf",
        "мамапапа",
        "leavemealone",
        "сумерки",
        "rfntymrf",
        "константин",
        "132435",
        "vfhufhbnf",
        "россия",
        "787898",
        "tytxrf",
        "манюня",
        "12qwaszx",
        "yfcntyf",
        "Анастасия",
        "лерочка",
        "rjhjktdf",
        "Александр",
        "derparol",
        "nokia3250",
        "rtyuehe",
        "kNOpKA",
        "сережа",
        "iriska",
        "zvezda",
        "zxcasdqwe",
        "писька",
        "клубничка",
        "vjkjrj",
        "zaraza",
        "хуйвам",
        "сиськи",
        "qwerty1234",
        "cfvceyu",
        "blbntyf",
        "192837",
        "123698745",
        "ericsson",
        "lenochka",
        "tokiohotel",
        "nastenka",
        "надежда",
        "vladislav",
        "ghjcnjnfr",
        "112358",
        "911911",
        "14881488",
        "162534",
        "maximka",
        "asdfghjk",
        "angelok",
        "gjkbyf",
        "12345q",
        "andrei",
        "tarakan",
        "respect",
        "alexey",
        "dthjybrf",
        "1q1q1q",
        "машенька",
        "123456789a",
        "настюшка",
        "vjqgfhjkm",
        "syncmaster",
        "самсунг",
        "танюшка",
        "ghbrjk",
        "galina",
        "crjhgbjy",
        "heckfy",
        "tdutybz",
        "николай",
        "hjccbz",
        "321678",
        "собака",
        "753159",
        "kazantip",
        "kleopatra",
        "mamapapa",
        "koshka",
        "юленька",
        "карина",
        "gbgbcmrf",
        "свобода",
        "090909",
        "lacoste",
        "стерва",
        "kjkszpj",
        "777555",
        "f,hfrflf,hf",
        "tecktonik",
        "ghblehjr",
        ".ktymrf",
        "loveis",
        "dfkthf",
        "malina",
        "gbcmrf",
        "koroleva",
        "565656",
        "Андрей",
        "юлечка",
        "cgfhnfr",
        "19411945",
        "aleksei",
        "rjycnfynby",
        "z nt,z k.,k.",
        "azsxdc",
        "malish",
        "123321123",
        "gfhjkmgfhjkm",
        "dfktynbyf",
        "настена",
        "viktoria",
        "dinamo",
        "satana",
        "adgjmp",
        "eqdfv",
        "nastena",
        "ранетки",
        "olenka",
        "stigmata",
        "любимка",
        "verbatim",
        "irishka",
        "margarita",
        "mamochka",
        "идитенахуй",
        "mashka",
        "cthtuf",
        "123zxc",
        "яночка",
        "171717",
        "dashka",
        "1q2w3e4r5",
        "konstantin",
        "машина",
        "blondinka",
        "rfvfcenhf",
        "qwqwqw",
        "kaktus",
        "123qweasdzxc",
        "newlife",
        "cbcmrb",
        "nastia",
        "fktyrf",
        "кукушка",
        "electro",
        "123456654321",
        "medved",
        "qwert12345",
        "       ",
        "москва",
        "jktxrf",
        "kjrjvjnbd",
        "lolita",
        "rhfcfdbwf",
        "виталик",
        "hfytnrb",
        "андрюша",
        "дашенька",
        "ванечка",
        "zxzxzx",
        "валерия",
        "ijrjkfl",
        "женька",
        "nfy.irf",
        "135792468",
        "adrenalin",
        "zaebali",
        "valentina",
        "gettherefast",
        "Максим",
        "тектоник",
        "nissan",
        "фывапро",
        "qwertyuio",
        "нескажу",
        "дашуля",
        "оксана",
        "vjcrdf",
        "придурок",
        "1q2w3e4",
        "poiuytrewq",
        "katrin",
        "танюша",
        "заебали",
        "q1q1q1",
        "анюточка",
        "maksimka",
        "k.,k.tuj",
        "dfcbkbq",
        "йййййй",
        "linkin",
        "бесит",
        "бог",
        "рамзес",
        "египет",
        "жизнь",
        "Вк",
        "Вконтакте",
        "вк",
        "химия",
        "физика",
        "военком",
        "ВК",
        "ВКОНТАКТЕ",
        "ЛОЛ",
        "Лол",
        "КЕК",
        "Кек",
        "лол",
        "кек",
        "пидр",
        "иди нахуй",
        "хуй",
        "соси",
        "пиздюк",
        "хуй тебе",
        "хер",
        "админ",
        "нуб",
        "сложна",
        "залупа",
        "моча",
        "говно",
        "баребух",
        "негр",
        "ха",
        "хах",
        "хаха",
        "хахах",
        "ххх",
        "ааа",
        "сука",
        "ахах",
        "ахаха",
        "ахахах",
        "пхп",
        "пхпх",
        "пхпхп",
        "пхах",
        "пхпхпх",
        "блять",
        "шлюха",
        "блядь",
        "бля",
        "ахуеть",
        "хуею",
        "кайф",
        ".",
        ";",
        "крест",
        "кошка",
        "собака некрещённая",
        "собака некрещенная",
        "заебись",
        "люблюмаму",
        "крутойшкольник",
        "нешкольник",
        "школьник228",
        "школьник",
        "школа",
        "блин",
        "путин",
        "обама",
        "сирия",
        "пиздим его",
        "люблю маму",
        "люблю папу",
        "папа",
        "мама",
        "сын",
        "дочка",
        "мальчик",
        "девочка",
        "олух",
        "чмо",
        "пизда",
        "очко",
        "мозг",
        "пароль123"
    ];
    t1.forEach(function(a1){
        if(!(keyss.indexOf(a1)+1))keyss.push(a1);
    });
}
getWords1();