itemCombinations([
    ["Impact Bomb", "Discombobulated White Cube",],
    ["Discombobulated White Cube", "Impact Bomb", "Storage Cube",],
    ["Magenta Cube", "Green Cube", "Blue Cube", "Grass Cube", "Armor Cube",],
    ["Green Cube", "Wooden Wall", "Wealth Cube", "Plate Cube", "Mud Cube", "Soil Cube", "Metal Wall", "Blue Cube", "Stone Wall", "Red Cube", "Concrete Wall", "Yellow Cube", "Hyper Fragment", "Magenta Cube",],
    ["Cyan Cube", "Copper", "Red Cube", "Air Cube",],
    ["Helmet Cube", "Gold Cube", "Copper Cube", "Pyrolite Cube", "Iron Cube",],
    ["Red Cube", "Armor Cube", "Wealth Cube", "Cyan Cube", "Concrete Wall", "Forge Cube", "Metal Wall", "Wooden Wall", "Blue Cube", "White Cube", "Stone Wall", "Green Cube", "Iron", "Yellow Cube", "Wood Cube",],
    ["Club", "Forge Cube", "Spike",],
    ["Charged Power Cube", "Mage Staff", "Raider Brute Respawner", "Goldplate Cube", "Battery Cube", "Mechanical Obliterator Respawner", "Hammerdom Respawner",],
    ["Rock Cube", furnaceProcess, "Iron Cube", "Molten Sphere", "Steam Cube",],
    ["Wood Cube", "Armor Cube", "Dirt Cube", "Red Cube", "Plate Cube", "Forge Cube", "Stone Barricade", "Iron Cube", "Iron", "Blade",],
    ["Yellow Cube", "Armor Cube", "Green Cube", "Red Cube", "Blue Cube",],
    ["Dirt Cube", furnaceProcess, "Water Cube", "Wood Cube",],
    ["Wealth Cube", "Red Cube", "Container Cube", "Greatsword", "Green Cube", "Steel Cube", "Plate Cube", "Blue Cube", "Enricher", "Healer Cube", "Power Cube",],
    ["Blue Cube", "Armor Cube", "Wealth Cube", "Wooden Wall", "Green Cube", "Magenta Cube", "Metal Wall", "Forge Cube", "Gold Cube", "Stone Wall", "Red Cube", "Concrete Wall", "Yellow Cube", "Conveyor Belt",],
    ["White Cube", furnaceProcess, "Chromium", "Steam Cube", "Pyrolite", "Gold", "Lava Cube", "Rusted Iron", "Chlorophyte", "Slightly Oxidised Copper", "Slightly Oxidised Copper", "Heavily Oxidised Copper", "Red Cube", "Steel", "Iron", "Copper", "Cryoide", "Corruption",],
    ["Super-Charged Power Cube", "Cryoide Cube", "Power Cube Cage", "Sledgehammer",],
    ["Power Cube Cage", "Super-Charged Power Cube",],
    ["Contained Super-Charged Power Cube", "Entity Infuser",],
    ["Pack Cube", "Plate Cube",],
    ["Steel", "White Cube",],
    ["Steel Cube", "Iron Chestplate", "Wealth Cube", "Iron Leggings", "Concrete Door Wall", "Backpack Cube", "Metal Wall", "Iron Helmet", "Iron Boots",],
    ["Spike", "Iron", "Plate Cube", "Club",],
    ["Glacier Club", "Cryoide Cube",],
    ["Frozen Club", "Glacier Cube",],
    ["Backpack Cube", "Steel Cube",],
    ["Gunpowder Cube", "Throwable Cube",],
    ["Conveyor Belt", "Enriched Red Cube", "Purple Cube", "Blue Cube",],
    ["Sledgehammer", "Super-Charged Power Cube",],
    ["Wet Concrete Cube", furnaceProcess,],
    ["Concrete Cube", "Iron Cube",],
    ["Sand Cube", furnaceProcess, "Water Cube",],
    ["Wet Sand Cube", "Mud Cube",],
    ["Mud Cube", furnaceProcess, "Wet Sand Cube", "Green Cube",],
    ["Soil Cube", "Green Cube", "Wooden Wall",],
    ["Wooden Wall", "Red Cube", "Soil Cube", "Green Cube", "Blue Cube",],
    ["Concrete Barricade", "Charged Battery Cube", "Plate Cube", "Concrete Wall",],
    ["Concrete Wall", "Concrete Barricade", "Red Cube", "Green Cube", "Blue Cube",],
    ["Stick", "Metalic Cube", "Rusted Iron Cube", "Wooden Barricade", "Enrichment Cube", "Plate Cube", "Rage Hammer Head", "Powerful Magic Crystal", "Great Hammer Head",],
    ["Copper", furnaceProcess, "White Cube", "Cyan Cube", "Dagger", "Forge Cube",],
    ["Copper Cube", furnaceProcess, "Chestplate Cube", "Boots Cube", "Greatsword", "Longsword", "Speed Coil", "Energy Cube", "Sword", "Spear", "Helmet Cube", "Iron Cube", "Leggings Cube",],
    ["Iron", furnaceProcess, "Steam Cube", "White Cube", "Red Cube", "Spike", "Dagger", "Forge Cube", "Wood Cube",],
    ["Iron Cube", furnaceProcess, "Chestplate Cube", "Copper Cube", "Steam Cube", "Reinforced Club", "Boots Cube", "Plate Cube", "Wood Cube", "Forge Cube", "Gold Cube", "Helmet Cube", "Rock Cube", "Armor Cube", "Concrete Cube", "Leggings Cube",],
    ["Gold", furnaceProcess, "Dagger", "White Cube", "Cryoide Dust",],
    ["Gold Cube", furnaceProcess, "Chestplate Cube", "Forge Cube", "Spear", "Reinforced Club", "Longsword", "Sword", "Blue Cube", "Boots Cube", "Helmet Cube", "Iron Cube", "Leggings Cube",],
    ["Permafrost Cube", furnaceProcess, "Frost Spear", "Frozen Greatsword", "Cryoide Dust", "Frost Sword",],
    ["Glacier Cube", furnaceProcess, "Ice Spear", "Ice Sword", "Frost Greatsword", "Ice Longsword", "Ice Dagger", "Lava Cube", "Frozen Club", "Glacier Cube", "Caltrop",],
    ["Ice Cube", furnaceProcess, "Water Cube", "Golden Longsword", "Golden Dagger", "Golden Sword", "Golden Spear", "Iron Club", "Golden Greatsword",],
    ["Water Cube", furnaceProcess, "Sand Cube", "Dirt Cube", "Ice Cube", "Plasma Cube",], // ashProcess
    ["Steam Cube", furnaceProcess, "Iron Cube", "White Cube", "Rock Cube", "Iron",],
    ["Plasma Cube", "Water Cube", "Lava Cube", "Cooled Lava Cube",],
    ["Pyrolite", "White Cube", "Dagger", "Enricher",],
    ["Stone Wall", "Red Cube", "Green Cube", "Blue Cube",],
    ["Metalic Cube", "Stick", "Greatsword", "Complete Combustion Engine",],
    ["Concrete Door Wall", "Steel Cube",],
    ["Blossom Cube", "Copper Leggings",],
    ["Soul Cube", "Death Cube",],
    ["Death Cube", "Soul Cube", "Max Health Increaser",],
    ["Max Health Increaser", "Death Cube",],
    ["Leggings Cube", "Gold Cube", "Copper Cube", "Iron Cube", "Pyrolite Cube",],
    ["Helmet Cube", "Gold Cube", "Copper Cube", "Pyrolite Cube", "Iron Cube",],
    ["Boots Cube", "Gold Cube", "Copper Cube", "Iron Cube", "Pyrolite Cube",],
    ["Chestplate Cube", "Gold Cube", "Copper Cube", "Iron Cube", "Pyrolite Cube",],
    ["Iron Shield", "Spiked Cube", "Plate Cube",],
    ["Iron Helmet", "Spiked Cube", "Steel Cube",],
    ["Iron Leggings", "Spiked Cube", "Steel Cube",],
    ["Iron Chestplate", "Steel Cube", "Spiked Cube",],
    ["Iron Boots", "Steel Cube", "Spiked Cube",],
    ["Heavy Iron Shield", "Spiked Cube",],
    ["Pyrolite Chestplate", "Cryoide Chestplate",],
    ["Pyrolite Leggings", "Cryoide Leggings",],
    ["Pyrolite Helmet", "Cryoide Helmet",],
    ["Pyrolite Boots", "Cryoide Boots",],
    ["Copper Leggings", "Blossom Cube",],
    ["Engine Cylinder", "Engine Cylinder",],
    ["Great Hammer Head", "Gilded Stick", "Stick",],
    ["Double Engine Cylinder", "Double Engine Cylinder",],
    ["Spiked Cube", "Iron Chestplate", "Heavy Iron Shield", "Iron Leggings", "Iron Helmet", "Iron Shield", "Iron Boots",],
    ["Quad Engine Cylinder", "Engine Piston",],
    ["Engine Piston", "Quad Engine Cylinder",],
    ["Chromium Ring", "Enlarged Engine",],
    ["Flame Sword", "Golden Sword", "Permafrost Sword"],
    ["Gravity Coil", "Speed Coil", "Enriched Blue Cube",],
    ["Armor Cube", "Blue Cube", "Iron Cube", "Red Cube", "Yellow Cube", "Wood Cube", "Magenta Cube",],
    ["Lava Cube", "Golden Spear", "White Cube", "Caltrop", "Ice Longsword", "Plasma Cube", "Explosive Cube", "Golden Greatsword", "Ice Sword", "Ice Dagger", "Golden Longsword", "Golden Sword", "Glacier Cube", "Ice Spear", "Iron Club", "Frost Greatsword",],
    ["Cooled Lava Cube", "Plasma Cube", "Goldplate Cube",],
    ["Forge Cube", "Red Cube", "Regen Cube", "Hammer", "Plate Cube", "Club", "Blue Cube", "Gold Cube", "Iron Cube", "Iron", "Copper", "Wood Cube",],
    ["Plate Cube", "Green Cube", "Wealth Cube", "Wooden Barricade", "Spike", "Iron Shield", "Acid Cube", "Stick", "Forge Cube", "Metal Barricade", "Stone Barricade", "Pack Cube", "Spiked Iron Shield", "Concrete Barricade", "Flesh Barricade", "Wood Cube", "Iron Cube",],
    ["Spiked Iron Shield", "Plate Cube",],
    ["Flesh Cube", "Chromium Cube",],
    ["Chromium", furnaceProcess, "Chromium Cube", "White Cube",],
    ["Chromium Cube", furnaceProcess, "Chromium", "Conveyor Belt",],
    ["Conveyor Belt", "Enriched Red Cube", "Purple Cube", "Chromium Cube", "Blue Cube",],
    ["Filter Conveyor Belt", "Teal Cube",],
    ["Rusted Iron", furnaceProcess, "Caltrop", "White Cube",],
    ["Rusted Iron Cube", furnaceProcess, "Stick",],
    ["Pusher", "Combustion Engine Piston",],
    ["Gilded Great Hammer", "Enriched White Cube",],
    ["Enriched Red Cube", "Enriched Magenta Cube", "Speed Coil", "Enriched Blue Cube", "Enriched Yellow Cube", "Enriched Green Cube", "Enriched Cyan Cube", "Conveyor Belt",],
    ["Enriched Blue Cube", "Enriched Yellow Cube", "Gravity Coil", "Enriched Green Cube", "Enriched Magenta Cube", "Enriched Red Cube",],
    ["Enriched Green Cube", "Enriched Yellow Cube", "Enriched Magenta Cube", "Enriched Blue Cube", "Enriched Red Cube", "Enriched Cyan Cube", "Regen Cube",],
    ["Enriched Magenta Cube", "Enriched Green Cube", "256 Cube", "Enriched Blue Cube", "Enriched Red Cube",],
    ["Enriched Yellow Cube", "Enriched Green Cube", "Enriched Red Cube", "Enriched Blue Cube",],

    ["Enriched White Cube", furnaceProcess, "Gilded Great Hammer", "Rage Hammer", "Gilded Rage Hammer", "Great Hammer",],
    ["Enriched Black Cube", "Golden Spear", "Golden Longsword", "Sword", "Golden Dagger", "Metal Wall", "Golden Greatsword",],
    ["Metal Wall", "Green Cube", "Enriched Black Cube", "Red Cube", "Steel Cube", "Blue Cube",],
    ["Metal Wall", "Green Cube", "Enriched Black Cube", "Red Cube", "Steel Cube", "Blue Cube",],
    ["Teal Cube", "Filter Conveyor Belt",],
    ["Quarks", "Quarks",],
    ["Nucleus", "Nucleus",],
    ["Matter", "Matter",],
    ["Preons", acceleratorProcess, "Preons",],
    ["Destroyed Particles", compressorProcess,],

    ["2 Cube", "2 Cube",],
    ["4 Cube", "4 Cube",],
    ["8 Cube", "8 Cube",],
    ["16 Cube", "16 Cube",],
    ["32 Cube", "32 Cube",],
    ["64 Cube", "64 Cube",],

    ["Vault",],
    ["Destroyed Particles",],
    ["Mechanical Glove",],
    ["Clock",],
    ["Great Longsword",],
    ["Night Vision Goggles",],
    ["Fire",],
    ["Ramp Conveyor Belt",],
    ["Fast Conveyor Belt",],
    ["Health Cube",],
    ["Concrete Ladder Wall",],
    ["Concrete Window Wall",],
    ["Wooden Shield",],
    ["Rusty Caltrop",],
    ["Blossom Leggings",],
    ["Iron Greatsword",],
    ["Spiked Club",],
    ["Multi Cube",],
    ["Heavy Spiked Iron Shield",],
    ["Max Health Decreaser",],
    ["Cruelty Cube",],
    ["Grindstone",],
    ["Fiery Greatsword",],
    ["Activated Gilded Great Hammer",],
    ["Portable Disposer",],
    ["Inverted Filter Conveyor Belt",],
]);