itemCombinations([
    ["Impact Bomb Cube", "Discombobulated White Cube",],
    ["Magenta Cube", "Green Cube", "Blue Cube", "Grass Cube", "Armor Cube",],
    ["Green Cube", "Wooden Wall", "Wealth Cube", "Plate Cube", "Mud Cube", "Soil Cube", "Metal Wall", "Blue Cube", "Stone Wall", "Red Cube", "Concrete Wall", "Yellow Cube", "Hyper Fragment", "Magenta Cube",],
    ["Cyan Cube", "Copper", "Red Cube", "Air Cube",],
    ["Helmet Cube", "Gold Cube", "Copper Cube", "Pyrolite Cube", "Iron Cube",],
    ["Red Cube", "Armor Cube", "Wealth Cube", "Cyan Cube", "Concrete Wall", "Forge Cube", "Metal Wall", "Wooden Wall", "Blue Cube", "White Cube", "Stone Wall", "Green Cube", "Iron", "Yellow Cube", "Wood Cube",],
    ["Club", "Forge Cube", "Spike",],
    ["Charged Power Cube", "Mage Staff", "Raider Brute Respawner", "Goldplate Cube", "Battery Cube", "Mechanical Obliterator Respawner", "Hammerdom Respawner",],
    ["Rock Cube", furnaceProcess, "Iron Cube", "Molten Sphere", "Steam Cube",],
    ["Wood Cube", "Armor Cube", "Dirt Cube", "Red Cube", "Plate Cube", "Forge Cube", "Stone Barricade", "Iron Cube", "Iron", "Blade",],
    ["Yellow Cube", "Armor Cube", "Green Cube", "Red Cube", "Blue Cube",],
    ["Dirt Cube", furnaceProcess, "Water Cube", "Wood Cube",],
    ["Wealth Cube", "Red Cube", "Container Cube", "Greatsword", "Green Cube", "Steel Cube", "Plate Cube", "Blue Cube", "Enricher", "Healer Cube", "Power Cube",],
    ["Blue Cube", "Armor Cube", "Wealth Cube", "Wooden Wall", "Green Cube", "Magenta Cube", "Metal Wall", "Forge Cube", "Gold Cube", "Stone Wall", "Red Cube", "Concrete Wall", "Yellow Cube", "Conveyor Belt",],
    ["White Cube", furnaceProcess, "Chromium", "Steam Cube", "Pyrolite", "Gold", "Lava Cube", "Rusted Iron", "Chlorophyte", "Slightly Oxidised Copper", "Slightly Oxidised Copper", "Heavily Oxidised Copper", "Red Cube", "Steel", "Iron", "Copper", "Cryoide", "Corruption",],
    ["Super-Charged Power Cube", "Cryoide Cube", "Power Cube Cage", "Sledgehammer",],
    ["Pack Cube", "Plate Cube",],
    ["Backpack Cube", "Steel Cube",],
    ["Permafrost Cube", furnaceProcess, "Frost Spear", "Frozen Greatsword", "Cryoide Dust", "Frost Sword",],
    ["Glacier Cube", furnaceProcess, "Ice Spear", "Ice Sword", "Frost Greatsword", "Ice Longsword", "Ice Dagger", "Lava Cube", "Frozen Club", "Glacier Cube", "Caltrop",],
    ["Ice Cube", furnaceProcess, "Water Cube", "Golden Longsword", "Golden Dagger", "Golden Sword", "Golden Spear", "Iron Club", "Golden Greatsword",],
    ["Water Cube", furnaceProcess, "Sand Cube", "Ash Sifter", "Dirt Cube", "Ice Cube", "Plasma Cube",],
    ["Steam Cube", furnaceProcess, "Iron Cube", "White Cube", "Rock Cube", "Iron",],
    ["Plasma Cube", "Water Cube", "Lava Cube", "Cooled Lava Cube",],
    ["Lava Cube", "Golden Spear", "White Cube", "Caltrop", "Ice Longsword", "Plasma Cube", "Explosive Cube", "Golden Greatsword", "Ice Sword", "Ice Dagger", "Golden Longsword", "Golden Sword", "Glacier Cube", "Ice Spear", "Iron Club", "Frost Greatsword",],
    ["Cooled Lava Cube", "Plasma Cube", "Goldplate Cube",],

    ["2 Cube", "2 Cube",],
    ["4 Cube", "4 Cube",],
    ["8 Cube", "8 Cube",],
    ["16 Cube", "16 Cube",],
    ["32 Cube", "32 Cube",],
    ["64 Cube", "64 Cube",],
]);