locationItem([
  [compressorProcess, "Compressor Island"],
  [entityInfuser, "Entity Infuser Island"],
  [furnaceProcess, "Spawn"],
  [timeProcess, "Everywhere"],

  ["Red Cube", "Spawn"],
  ["Green Cube", "Spawn"],
  ["Blue Cube", "Spawn"],
  ["White Cube", "Spawn"],
  ["Dirt Cube", "Spawn"],
  ["Wood Cube", "Spawn"],
  ["Rock Cube", "Spawn"],
  ["Ice Cube", "Spawn"],

  ["Pain Cube", "Underworld"],
  ["Crimson Cube", "Underworld"],
  ["Flesh Cube", "Underworld"],
  ["Fire", "Underworld"],

  ["Magic Crystal", "Enchanter Island"],
]);

lootItem([
  ["Contained Super-Charged Power Cube", "Charged Tank",],
  ["Steel", "Charged Tank",],
  ["Engine Piston", "Raider Knight",],

  ["Venom", "Arachna",],
  ["Chlorophyte", "Arachna",],

  ["Enriched Pyrolite", "Guardian Of The Underworld"],

  ["Sword", "Raider"],
  ["Flame Sword", "Raider"],
  ["Great Longsword", "Ravenscar"],
  ["Longsword", "Longsworded Rider"],
  ["Greatsword", "Cube Destroyer"],
  ["Silver Sword", unknownItem],
  ["Lava Greatsword", "Pyro"],
  ["Iron Greatsword", "Raider Brute"],
  ["Ice Greatsword", unknownItem],
  ["Fiery Greatsword", "Guardian Of The Underworld"],
  ["Cursed Sword", unknownItem],
  ["Glacier Greatsword", unknownItem],
  ["Upgraded Lava Greatsword", unknownItem],
  ["Upgraded Iron Greatsword", unknownItem],
  ["Goldfire Greatsword", unknownItem],
  ["Venom Greatsword", unknownItem],

  ["Raider Brute Helmet", "Raider Brute"],

  ["Mage Staff", "White Beard"],
  ["Tank Summoner Staff", unknownItem],
  ["Heavy Tank Summoner Staff", unknownItem],

  ["Enchant Token", "White Beard"],

  ["Hammerdom Helmet", "Hammerdom"],
  ["Great Hammer Head", "Hammerdom"],
  ["Activated Hammerdom Helmet", unknownItem],
  ["Rage Hammer Head", unknownItem],
  ["Deactivated Upgraded Hammerdom Helmet", unknownItem],
  ["Deactivated Upgraded Rage Hammer", unknownItem],
  ["Hammerdom Chestplate", unknownItem],

  ["Night Vision Goggles", "Ravenscar"],
  ["Clock", "Ravenscar"],
  ["Clock", "Ravenscar"],
  
  ["Light Cube", "Longsworded Rider"],

  ["Plate Cube", "Mechanical Obliterator"],
  ["Wealth Cube", "Mechanical Obliterator"],
  ["Goldplate Cube", "Mechanical Obliterator"],
  ["Mechanical Glove", "Mechanical Obliterator"],

  ["Dash Cube", "Cube Destroyer"],
  ["Green Cube", "Cube Destroyer"],
  ["White Cube", "Cube Destroyer"],
  ["Multi Cube", "Cube Destroyer"],
  ["Spike", "Cube Destroyer"],

  ["Club", "Raider"],
  ["Spiked Club", "Raider"],
])

infuserItem([
  ["Cube Destroyer Respawner", "Contained Super-Charged Power Cube", "Multi Cube"],
  ["Raider Brute Respawner", "Contained Super-Charged Power Cube", "Iron Greatsword", "Raider Brute Helmet"],
]);

craftItem([
  ["Yellow Cube", "Red Cube", "Green Cube"],
  ["Orange Cube", "Yellow Cube", "Red Cube"],
  ["Lime Cube", "Yellow Cube", "Green Cube"],

  ["Magenta Cube", "Red Cube", "Blue Cube"],
  ["Purple Cube", "Magenta Cube", "Blue Cube"],

  ["Cyan Cube", "Green Cube", "Blue Cube"],
  ["Turquoise Cube", "Cyan Cube", "Blue Cube"],
  ["Teal Cube", "Cyan Cube", "Green Cube"],
  ["Caltrop", "Cyan Cube", "Copper"],
  ["Flaming Caltrop", "Caltrop", "Lava Cube"],
  ["Glacier Caltrop", "Caltrop", "Glacier Cube"],
  ["Rusty Caltrop", "Caltrop", "Rusted Iron"],

  ["White Cube", "Magenta Cube", "Green Cube"],
  ["White Cube", "Cyan Cube", "Red Cube"],
  ["White Cube", "Yellow Cube", "Blue Cube"],

  
  ["Enriched Red Cube", "Wealth Cube", "Red Cube"],
  ["Enriched Green Cube", "Wealth Cube", "Green Cube"],
  ["Enriched Blue Cube", "Wealth Cube", "Blue Cube"],

  ["Enriched Yellow Cube", "Enriched Red Cube", "Enriched Green Cube"],
  ["Enriched Magenta Cube", "Enriched Red Cube", "Enriched Blue Cube"],
  ["Enriched Cyan Cube", "Enriched Blue Cube", "Enriched Green Cube"],
  ["Enriched Lime Cube", "Enriched Yellow Cube", "Enriched Green Cube"],
  ["Enriched Turquoise Cube", "Enriched Cyan Cube", "Enriched Blue Cube"],
  ["Enriched White Cube", "Enriched Magenta Cube", "Enriched Green Cube"],
  ["Enriched White Cube", "Enriched Yellow Cube", "Enriched Blue Cube"],
  ["Enriched White Cube", "Enriched Cyan Cube", "Enriched Red Cube"],
  ["Enriched Black Cube", "Enriched White Cube", furnaceProcess],
  ["Enriched Violet Cube", "Enriched Magenta Cube", "Enriched Red Cube"],
  ["Enriched Orange Cube", "Enriched Yellow Cube", "Enriched Red Cube"],
  ["Enriched Purple Cube", "Enriched Magenta Cube", "Enriched Blue Cube"],
  ["Enriched Teal Cube", "Enriched Cyan Cube", "Enriched Green Cube"],
  
  ["Enriched Speed Coil", "Speed Coil", "Enriched Red Cube"],
  ["Enriched Gravity Coil", "Gravity Coil", "Enriched Blue Cube"],
  ["Restore Cube", "Regen Cube", "Enriched Green Cube"],
  ["Enriched Pyrolite", "Enricher", "Pyrolite"],
  ["Portable Disposer", "Enriched Black Cube", "Metal Wall"],
  ["252 Cube", "256 Cube", "Enriched Magenta Cube"],

  ["2 Cube", "White Cube", "Red Cube"],
  ["4 Cube", "2 Cube", "2 Cube"],
  ["8 Cube", "4 Cube", "4 Cube"],
  ["16 Cube", "8 Cube", "8 Cube"],
  ["32 Cube", "16 Cube", "16 Cube"],
  ["64 Cube", "32 Cube", "32 Cube"],
  ["128 Cube", "64 Cube", "64 Cube"],
  ["256 Cube", "128 Cube", "128 Cube"],
  ["512 Cube", "256 Cube", "256 Cube"],
  ["1024 Cube", "512 Cube", "512 Cube"],
  ["2048 Cube", "1024 Cube", "1024 Cube"],
  ["4096 Cube", "2048 Cube", "2048 Cube"],
  ["8192 Cube", "4096 Cube", "4096 Cube"],
  ["16384 Cube", "8192 Cube", "8192 Cube"],
  ["32768 Cube", "16384 Cube", "16384 Cube"],
  ["65536 Cube", "32768 Cube", "32768 Cube"],
  ["131072 Cube", "65536 Cube", "65536 Cube"],
  ["262144 Cube", "131072 Cube", "131072 Cube"],
  ["524288 Cube", "262144 Cube", "262144 Cube"],

  ["Pack Cube", "Wood Cube", "Dirt Cube"],
  ["Container Cube", "Pack Cube", "Plate Cube"],
  ["Backpack Cube", "Container Cube", "Wealth Cube"],

  ["Lava Cube", "Rock Cube", "Molten Sphere"],
  ["Activator Cube", "Lava Cube", "White Cube"],
  ["Cooled Lava Cube", "Lava Cube", "Glacier Cube"],
  ["Power Cube", "Cooled Lava Cube", "Plasma Cube"],
  ["Charged Power Cube", "Power Fragment", "Power Cube"],
  ["Super-Charged Power Cube", "Charged Power Cube", "Goldplate Cube"],
  ["Contained Super-Charged Power Cube", "Power Cube Cage", "Super-Charged Power Cube"],

  ["Permafrost Cube", "Glacier Cube", "Glacier Cube"],
  ["Glacier Cube", "Ice Cube", "Water Cube"],
  ["Sand Cube", "Steam Cube", "Rock Cube"],
  ["Wet Sand Cube", "Sand Cube", "Water Cube"],
  ["Mud Cube", "Dirt Cube", "Water Cube"],
  ["Soil Cube", "Mud Cube", "Green Cube"],
  ["Grass Cube", "Soil Cube", "Green Cube"],
  ["Flower Cube", "Grass Cube", "Magenta Cube"],
  ["Blossom Cube", "Flower Cube", "Enricher"],

  ["Wet Concrete Cube", "Mud Cube", "Wet Sand Cube"],
  ["Acid Cube", "Water Cube", "Plasma Cube"],
  ["Energy Cube", "Lava Cube", "Plasma Cube"],
  ["Light Cube", "Energy Cube", "Copper Cube"],

  ["Copper Cube", "White Cube", "Copper"],
  ["Iron Cube", "White Cube", "Iron"],
  ["Gold Cube", "White Cube", "Gold"],
  ["Pyrolite Cube", "White Cube", "Pyrolite"],
  ["Rusted Iron", "Steam Cube", "Iron"],
  ["Rusted Iron Cube", "Steam Cube", "Iron Cube"],
  ["Rusted Iron Cube", "White Cube", "Rusted Iron"],
  ["Slightly Oxidised Copper Cube", "White Cube", "Slightly Oxidised Copper"],
  ["Heavily Oxidised Copper Cube", "White Cube", "Heavily Oxidised Copper"],

  ["Air Cube", "Steam Cube", "White Cube"],
  ["Dash Cube", "Air Cube", "Cyan Cube"],

  ["Forge Cube", "Gold Cube", "Iron Cube"],
  ["Armor Cube", "Gold Cube", "Blue Cube"],
  ["Chestplate Cube", "Armor Cube", "Magenta Cube"],
  ["Pyrolite Chestplate", "Chestplate Cube", "Pyrolite Cube"],
  ["Boots Cube", "Armor Cube", "Yellow Cube"],
  ["Pyrolite Boots", "Boots Cube", "Pyrolite Cube"],
  ["Pyrolite Leggings", "Leggings Cube", "Pyrolite Cube",],
  ["Iron Shield", "Armor Cube", "Iron Cube"],
  ["Iron Helmet", "Helmet Cube", "Iron Cube"],
  ["Iron Chestplate", "Chestplate Cube", "Iron Cube",],
  ["Iron Boots", "Boots Cube", "Iron Cube",],
  ["Iron Leggings", "Leggings Cube", "Iron Cube"],
  ["Heavy Iron Shield", "Iron Shield", "Plate Cube"],
  ["Helmet Cube", "Armor Cube", "Blue Cube"],
  ["Pyrolite Helmet", "Helmet Cube", "Pyrolite Cube"],
  ["Leggings Cube", "Armor Cube", "Red Cube"],
  ["Pyrolite Leggings", "Leggings Cube", "Pyrolite Cube"],
  ["Copper Leggings", "Leggings Cube", "Copper Cube"],
  ["Blossom Leggings", "Copper Cube", "Blossom Cube"],
  ["Wooden Shield", "Armor Cube", "Wood Cube"],
  ["Plate Cube", "Forge Cube", "Iron Cube"],
  ["Power Cube Cage", "Plate Cube", "Iron Cube"],
  ["Metalic Cube", "Forge Cube", "Plate Cube"],
  ["Pusher", "Metalic Cube", "Stick"],
  ["Battery Cube", "Plate Cube", "Acid Cube"],
  ["Charged Battery Cube", "Battery Cube", "Charged Power Cube"],
  ["Wealth Cube", "Forge Cube", "Gold Cube"],
  ["Goldplate Cube", "Wealth Cube", "Plate Cube"],
  ["Enricher", "Goldplate Cube", "Cooled Lava Cube"],
  ["Enrichment Cube", "Enricher", "Wealth Cube"],
  ["Gilded Stick", "Enrichment Cube", "Stick"],

  ["Healer Cube", "Plate Cube", "Green Cube"],
  ["Life Cube", "Healer Cube", "Enrichment Cube"],
  ["Soul Cube", "Life Cube", "Power Cube"],
  ["Cruelty Cube", "Soul Cube", "Death Cube"],
  ["Max Health Increaser", "Life Cube", "Healer Cube"],
  ["Max Health Decreaser", "Max Health Increaser", "Death Cube"],
  ["Regen Cube", "Healer Cube", "Wealth Cube"],
  ["Restore Cube", "Regen Cube", "Enriched Green Cube"],
  ["Health Cube", "Regen Cube", "Healer Cube"],
  ["Regen Coil", "Regen Cube", "Forge Cube"],
  ["Restoration Coil", "Regen Cube", "Restore Cube"],

  ["Raider Brute Resummoner", "Charged Power Cube", "Raider Brute Respawner"],
  ["Hammerdom Resummoner", "Hammerdom Respawner", "Charged Power Cube"],
  ["Mechanical Obliterator Resummoner", "Charged Power Cube", "Mechanical Obliterator Respawner"],

  ["Spiked Cube", "Spike", "Plate Cube"],
  ["Engine Cylinder", "Spike", "Iron"],
  ["Double Engine Cylinder", "Engine Cylinder", "Engine Cylinder"],
  ["Quad Engine Cylinder", "Double Engine Cylinder", "Double Engine Cylinder"],
  ["Combustion Engine Piston", "Quad Engine Cylinder", "Engine Piston",],
  ["Complete Combustion Engine", "Combustion Engine Piston", "Pusher",],
  ["Enlarged Engine", "Complete Combustion Engine", "Metalic Cube",],
  [acceleratorProcess, "Enlarged Engine", "Chromium Ring"],

  ["Steel Cube", "White Cube", "Steel"],
  ["Storage Cube", "Backpack Cube", "Steel Cube"],
  ["Equinox Storage Cube", "Storage Cube", "Discombobulated White Cube"],
  ["Clock", "Wealth Cube", "Steel Cube"],

  ["Spiked Iron Shield", "Spiked Cube", "Iron Shield"],
  ["Heavy Spiked Iron Shield", "Heavy Iron Shield", "Spiked Cube"],
  ["Heavy Spiked Iron Shield", "Plate Cube", "Spiked Iron Shield"],

  ["Light Sword", "Golden Sword", "Light Cube"],
  ["Sword", "Forge Cube", "Iron"],
  ["Sword", "Blade", "Wood Cube"],
  ["Ice Sword", "Golden Sword", "Ice Cube"],
  ["Dark Sword", "Enriched Black Cube", "Sword"],
  ["Air Sword", "Golden Sword", "Air Cube"],
  ["Copper Sword", "Copper Cube", "Sword"],
  ["Water Sword", "Lava Cube", "Ice Sword"],
  ["Golden Sword", "Sword", "Gold Cube"],
  ["Permafrost Sword", "Frost Sword", "Permafrost Cube"],
  ["Heavy Greatsword", "Greatsword", "Metalic Cube"],
  ["Water Longsword", "Lava Cube", "Ice Longsword"],
  ["Copper Longsword", "Longsword", "Copper Cube"],
  ["Flame Longsword", "Golden Longsword", "Lava Cube"],
  ["Frost Longsword", "Glacier Longsword", "Ice Longsword"],
  ["Golden Longsword", "Gold Cube", "Longsword"],
  ["Goldfire Longsword", "Golden Longsword", "Flame Longsword"],
  ["Ice Longsword", "Ice Cube", "Golden Longsword"],
  ["Pyrolite Longsword", "Pyrolite Cube", "Longsword"],
  ["Air Longsword", "Air Cube", "Golden Longsword"],
  ["Flow-Pow Longsword", "Flower Cube", "Golden Sword"],
  ["Flame Sword", "Lava Cube", "Golden Sword"],
  ["Goldfire Sword", "Flame Sword", "Golden Sword"],
  ["Frost Sword", "Ice Sword", "Glacier Cube"],
  ["Golden Greatsword", "Greatsword", "Wealth Cube"],
  ["Copper Greatsword", "Greatsword", "Copper Cube"],
  ["Pyrolite Sword", "Pyrolite Cube", "Sword"],
  ["Chlorophyte Sword", "Chlorophyte Cube", "Golden Sword"],
  ["Frostfire Longsword", "Flame Longsword", "Frost Longsword"],
  ["Dark Longsword", "Golden Longsword", "Enriched Black Cube"],
  ["Light Longsword", "Golden Longsword", "Light Cube"],
  ["Frostfire Sword", "Flame Sword", "Permafrost Sword"],
  ["Cryoide Sword", "Cryoide Cube", "Golden Sword"],
  ["Water Greatsword", "Frost Greatsword", "Lava Cube"],
  ["Fiery Greatsword", "Enthanogamer300's Bane", "Enthanogamer300's Bane"],
  ["Flame Greatsword", "Golden Greatsword", "Lava Cube"],
  ["Cryoide Longsword", "Golden Longsword", "Cryoide"],
  ["Chlorophyte Longsword", "Golden Longsword", "Chlorophyte Cube"],
  ["Frozen Greatsword", "Glacier Cube", "Frost Greatsword"],
  ["Frostbane Greatsword", "Permafrost Cube", "Frozen Greatsword"],
  ["Frost Greatsword", "Ice Cube", "Golden Greatsword"],
  ["Pyrolite Greatsword", "Greatsword", "Pyrolite Cube"],
  ["Silver Greatsword", "Greatsword", "Silver Sword"],
  ["Poison Greatsword", "Greatsword", "Venomshank"],
  ["Permafrost Greatsword", "Permafrost Crystal", "Glacier Greatsword"],
  ["Air Greatsword", "Golden Greatsword", "Air Cube"],
  ["Goldflame Greatsword", "Golden Greatsword", "Flame Greatsword"],
  ["Chlorophyte Greatsword", "Golden Greatsword", "Chlorophyte Cube"],
  ["Frostfire Greatsword", "Frostbane Greatsword", "Flame Greatsword"],
  ["Cryoide Greatsword", "Golden Greatsword", "Cryoide Cube"],
  ["Cursed Greatsword", "Greatsword", "Cursed Sword"],
  ["Light Greatsword", "Golden Greatsword", "Light Cube"],
  ["Dark Greatsword", "Golden Greatsword", "Enriched Black Cube"],

  ["Deactivated Hyper Cube", "Hyper Fragment", "Green Cube"],
  ["Hyper Cube", "Activator Cube", "Deactivated Hyper Cube"],
  ["Hyperblade", "Golden Sword", "Hyper Cube"],

  ["Club", "Red Cube", "Wood Cube"],
  ["Spiked Club", "Club", "Spike"],
  ["Golden Club", "Reinforced Club", "Gold Cube"],
  ["Reinforced Club", "Club", "Forge Cube"],
  ["Iron Club", "Reinforced Club", "Iron Cube"],
  ["Flaming Club", "Lava Cube", "Iron Club"],
  ["Glacier Club", "Glacier Club", "Frozen Club"],
  ["Frozen Club", "Iron Club", "Ice Cube"],
  ["Permafrost Club", "Glacier Club", "Cryoide Cube"],
  ["Ice Club", "Iron Club", "Ice Cube"],
  ["Goldfire Club", "Flaming Club", "Golden Club"],
  ["The Final Club", "Goldfire Club", "Permafrost Club"],
  
  ["Spear Stick", "Stick", "Rusted Iron Cube"],
  ["Light Spear", "Light Cube", "Golden Spear"],
  ["Air Spear", "Air Cube", "Golden Spear"],
  ["Ice Spear", "Ice Cube", "Golden Spear"],
  ["Permafrost Spear", "Permafrost Cube", "Frost Spear"],
  ["Flame Spear", "Lava Cube", "Frost Spear"],
  ["Copper Spear", "Copper Cube", "Spear"],
  ["Golden Spear", "Gold Cube", "Spear"],
  ["Water Spear", "Lava Cube", "Ice Spear"],
  ["Frost Spear", "Glacier Cube", "Ice Spear"],
  ["Spear", "Spear Stick", "Spear Head"],
  ["Pyrolite Spear", "Pyrolite Cube", "Spear"],
  ["Goldfire Spear", "Golden Spear", "Flame Spear"],
  ["Chlorophyte Spear", "Chlorophyte Cube", "Golden Spear"],
  ["Frostfire Spear", "Permafrost Spear", "Flame Spear"],
  ["Dark Spear", "Enriched Black Cube", "Golden Spear"],
  ["Cryoide Spear", "Cryoide Cube", "Golden Spear"],

  ["Hammer", "Wood Cube", "Iron"],
  ["Heavy Hammer", "Forge Cube", "Hammer"],
  ["Fortified Hammer", "Heavy Hammer", "Plate Cube"],
  ["Sledgehammer", "Stick", "Plate Cube"],
  ["Great Hammer", "Stick", "Great Hammer Head"],
  ["Rage Hammer", "Stick", "Rage Hammer Head"],
  ["Powerhammer", "Sledgehammer", "Super-Charged Power Cube"],
  ["Gilded Great Hammer", "Great Hammer Head", "Gilded Stick"],
  ["Gilded Great Hammer", "Enrichment Cube", "Great Hammer"],
  ["Gilded Rage Hammer", "Rage Hammer Head", "Gilded Stick"],
  ["Gilded Rage Hammer", "Enrichment Cube", "Rage Hammer"],
  ["Activated Gilded Great Hammer", "Enriched White Cube", "Gilded Great Hammer"],
  ["Activated Gilded Great Hammer", "Enrichment Cube", "Activated Great Hammer"],
  ["Activated Gilded Rage Hammer", "Enriched White Cube", "Gilded Rage Hammer"],
  ["Activated Gilded Rage Hammer", "Enrichment Cube", "Activated Rage Hammer"],
  ["Activated Great Hammer", "Enrichment White Cube", "Great Hammer"],
  ["Activated Rage Hammer", "Enrichment White Cube", "Rage Hammer"],
  ["Upgraded Activated Hammerdom Helmet", "Enriched Cyan Cube", "Deactivated Upgraded Hammerdom Helmet"],
  ["Upgraded Activated Gilded Rage Hammer", "Enriched Cyan Cube", "Deactivated Upgraded Rage Hammer"],

  ["Ally Cube", "Wealth Cube", "Power Cube"],
  ["Speed Coil", "Forge Cube", "Red Cube"],
  ["Gravity Coil", "Forge Cube", "Blue Cube"],
  ["Fusion Coil", "Speed Coil", "Gravity Coil"],
  ["Conveyor Belt", "Speed Coil", "Copper Cube"],
  ["Ramp Conveyor Belt", "Conveyor Belt", "Blue Cube"],
  ["Slope Conveyor Belt", "Conveyor Belt", "Yellow Cube"],
  ["Fast Conveyor Belt", "Conveyor Belt", "Enriched Red Cube"],
  ["Filter Conveyor Belt", "Conveyor Belt", "Chromium Cube"],
  ["Split Filter Conveyor Belt", "Left Filter Conveyor Belt", "Right Filter Conveyor Belt"],
  ["Right Filter Conveyor Belt", "Filter Conveyor Belt", "Red Cube"],
  ["Left Filter Conveyor Belt", "Filter Conveyor Belt", "Cyan Cube"],
  ["Double Right Filter Conveyor Belt", "Right Filter Conveyor Belt", "Chromium Cube"],
  ["Double Left Filter Conveyor Belt", "Left Filter Conveyor Belt", "Chromium Cube"],
  ["Alternating Conveyor Belt", "Conveyor Belt", "Purple Cube"],
  ["Switchable Conveyor Belt", "Alternating Conveyor Belt", "Purple Cube"],
  ["Bridger", "Wood Cube", "Plate Cube",],


  ["Blade", "Forge Cube", "Copper"],
  ["Stick", "Forge Cube", "Wood Cube"],
  ["Corruption Cube", "Corruption", "White Cube"],
  ["Chromium Cube", "Chromium", "White Cube"],

  
  ["Concrete Barricade", "Concrete Cube", "Iron Cube"],
  ["Metal Barricade", "Copper Cube", "Iron Cube"],
  ["Stone Barricade", "Rock Cube", "Iron Cube"],
  ["Wooden Barricade", "Wood Cube", "Iron Cube"],
  ["Flesh Barricade", "Chromium Cube", "Flesh Cube"],

  ["Concrete Door Wall", "Concrete Wall", "Blue Cube"],
  ["Metal Door Wall", "Metal Wall", "Blue Cube"],
  ["Stone Door Wall", "Blue Cube", "Stone Wall"],
  ["Wooden Door Wall", "Wooden Wall", "Blue Cube"],
  ["Wooden Wall", "Plate Cube", "Wooden Barricade"],
  ["Stone Wall", "Plate Cube", "Stone Barricade"],
  ["Metal Wall", "Metal Barricade", "Plate Cube"],
  ["Concrete Wall", "Plate Cube", "Concrete Barricade"],
  ["Concrete Window Wall", "Concrete Wall", "Green Cube"],
  ["Metal Window Wall", "Metal Wall", "Green Cube"],
  ["Stone Window Wall", "Stone Wall", "Green Cube"],
  ["Wooden Window Wall", "Wooden Wall", "Green Cube"],
  ["Concrete Ladder Wall", "Concrete Wall", "Red Cube"],
  ["Metal Ladder Wall", "Metal Wall", "Red Cube"],
  ["Stone Stair Wall", "Stone Wall", "Red Cube"],
  ["Wooden Ladder Wall", "Wooden Wall", "Red Cube"],
  ["Flesh Wall", "Plate Cube", "Flesh Barricade"],
  ["Reinforced Concrete Wall", "Concrete Wall", "Concrete Barricade"],

  ["Ladder", "Stick", "Wooden Barricade"],
  ["Lantern", "Wooden Barricade", "Light Cube"],
  ["Grindstone", "Stone Barricade", "Wood Cube"],
  [ashProcess, "Wooden Wall", "Soil Cube"],
  ["Anvil", "Metal Wall", "Steel Cube"],
  ["Vault", "Concrete Door Wall", "Steel Cube"],
  ["Teleportation Pad", "Concrete Barricade", "Charged Battery Cube"],

  ["Chromium Ring", "Chromium Cube", "Chromium"],
  ["Semi-Powerful Magic Crystal", "Magic Crystal", "Magic Crystal"],
  [
    "Powerful Magic Crystal",
    "Semi-Powerful Magic Crystal",
    "Semi-Powerful Magic Crystal",
  ],
  ["Mage Staff", "Powerful Magic Crystal", "Stick"],
  ["Charged Healer Staff", "Charged Mage Staff", "Regen Cube"],
  ["Charged Mage Staff", "Mage Staff", "Charged Power Cube"],
  ["Dual Tank Summoner Staff", "Heavy Tank Summoner Staff", "Tank Summoner Staff"],

  ["Throwable Cube", "Iron", "Red Cube"],
  ["Explosive Cube", "Throwable Cube", "Gunpowder Cube"],
  ["Bomb Cube", "Explosive Cube", "Lava Cube"],
  ["Impact Cube", "Explosive Cube", "Enrichment Cube"],
  ["Impact Bomb Cube", "Impact Cube", "Bomb Cube"],
  ["Fusion Bomb Cube", "Impact Bomb Cube", "Discombobulated White Cube"],

  ["Quarks", "Preons", "Preons"],
  ["Nucleus", "Quarks", "Quarks"],
  ["Matter", "Nucleus", "Nucleus"],
  ["Discombobulated White Cube", "Matter", "Matter"],
  ["Preons", "Destroyed Particles", compressorProcess],
  ["Destroyed Particles", "Preons", acceleratorProcess],
  ["Destroyed Particles", "Destroyed Particles", acceleratorProcess],

  [emptyItem, "Ash Cube", furnaceProcess],
  ["Dirt Cube", "Mud Cube", furnaceProcess],
  ["Glacier Cube", "Permafrost Cube", furnaceProcess],
  ["Ice Cube", "Glacier Cube", furnaceProcess],
  ["Water Cube", "Ice Cube", furnaceProcess],
  ["Steam Cube", "Water Cube", furnaceProcess],
  ["Plasma Cube", "Steam Cube", furnaceProcess],
  ["Copper", "Dirt Cube", furnaceProcess],
  ["Iron", "Dirt Cube", furnaceProcess],
  ["Gold", "Dirt Cube", furnaceProcess],
  ["Pyrolite", "Dirt Cube", furnaceProcess],
  ["Black Cube", "White Cube", furnaceProcess],
  ["Corruption", "Crimson Cube", furnaceProcess],
  ["Chromium", "Crimson Cube", furnaceProcess],
  ["Orb Of Crimson", "Crimson Cube", furnaceProcess],
  ["Death Cube", "Pain Cube", furnaceProcess],
  ["Molten Sphere", "Steel", furnaceProcess],
  ["Molten Sphere", "Steel Cube", furnaceProcess],
  ["Molten Sphere", "Rock Cube", furnaceProcess],
  ["Molten Sphere", "Copper", furnaceProcess],
  ["Molten Sphere", "Iron", furnaceProcess],
  ["Molten Sphere", "Rusted Iron", furnaceProcess],
  ["Molten Sphere", "Gold", furnaceProcess],
  ["Molten Sphere", "Slightly Oxidised Copper", furnaceProcess],
  ["Molten Sphere", "Heavily Oxidised Copper", furnaceProcess],
  ["Molten Sphere", "Copper Cube", furnaceProcess],
  ["Molten Sphere", "Iron Cube", furnaceProcess],
  ["Molten Sphere", "Rusted Iron Cube", furnaceProcess],
  ["Molten Sphere", "Gold Cube", furnaceProcess],
  ["Molten Sphere", "Slightly Oxidised Copper Cube", furnaceProcess],
  ["Molten Sphere", "Heavily Oxidised Copper Cube", furnaceProcess],
  ["Molten Sphere", "Corruption", furnaceProcess],
  ["Molten Sphere", "Corruption Cube", furnaceProcess],
  ["Molten Sphere", "Chromium", furnaceProcess],
  ["Molten Sphere", "Chromium Cube", furnaceProcess],
  ["Power Fragment", "Power Cube", furnaceProcess],
  ["Concrete Cube", "Wet Concrete Cube", furnaceProcess],
  ["Gunpowder Cube", "Sand Cube", furnaceProcess],

  ["Slightly Oxidised Copper", "Copper", timeProcess],
  ["Heavily Oxidised Copper", "Slightly Oxidised Copper", timeProcess],
  ["Slightly Oxidised Copper Cube", "Copper Cube", timeProcess],
  ["Heavily Oxidised Copper Cube", "Slightly Oxidised Copper Cube", timeProcess],
]);

ashItem([
  ["Mud Cube", "Ash Cube", ashProcess, "Water Cube"],
  ["Sand Cube", "Ash Cube", ashProcess, "Water Cube"],
  ["Forge Cube", "Ash Cube", ashProcess, "Water Cube"],

  ["Dirt Cube", "Ash Cube", ashProcess],
  ["Rock Cube", "Ash Cube", ashProcess],
  ["Gold", "Ash Cube", ashProcess],
  ["Iron", "Ash Cube", ashProcess],
  ["Copper", "Ash Cube", ashProcess],
  ["Gunpowder", "Ash Cube", ashProcess],
  ["White Cube", "Ash Cube", ashProcess],
]);