locationItem([
  ["Red Cube", "Spawn"],
  ["Green Cube", "Spawn"],
  ["Blue Cube", "Spawn"],
  ["White Cube", "Spawn"],
  ["Dirt Cube", "Spawn"],
  ["Wood Cube", "Spawn"],
  ["Rock Cube", "Spawn"],
  ["Ice Cube", "Spawn"],

  ["Pain Cube", "Underworld"],
  ["Crimson Cube", "Underworld"],
  ["Flesh Cube", "Underworld"],
  ["Fire", "Underworld"],

  ["Magic Crystal", "Magic Island"],
])

lootItem([
  ["Enriched Pyrolite", "Guardian Of The Underworld"],
])

craftItem([
  ["Yellow Cube", "Red Cube", "Green Cube"],
  ["Orange Cube", "Yellow Cube", "Red Cube"],
  ["Lime Cube", "Yellow Cube", "Green Cube"],

  ["Magenta Cube", "Red Cube", "Blue Cube"],
  ["Purple Cube", "Magenta Cube", "Blue Cube"],

  ["Cyan Cube", "Green Cube", "Blue Cube"],
  ["Caltrop", "Cyan Cube", "Copper"],
  ["Flaming Caltrop", "Caltrop", "Lava Cube"],
  ["Glacier Caltrop", "Caltrop", "Glacier Cube"],
  ["Rusty Caltrop", "Caltrop", "Rusted Iron"],

  ["White Cube", "Magenta Cube", "Green Cube"],
  ["White Cube", "Cyan Cube", "Red Cube"],
  ["White Cube", "Yellow Cube", "Blue Cube"],

  ["2 Cube", "White Cube", "Red Cube"],
  ["4 Cube", "2 Cube", "2 Cube"],
  ["8 Cube", "4 Cube", "4 Cube"],
  ["16 Cube", "8 Cube", "8 Cube"],
  ["32 Cube", "16 Cube", "16 Cube"],
  ["64 Cube", "32 Cube", "32 Cube"],

  ["Pack Cube", "Wood Cube", "Dirt Cube"],
  ["Container Cube", "Pack Cube", "Plate Cube"],
  ["Backpack Cube", "Container Cube", "Wealth Cube"],

  ["Lava Cube", "Rock Cube", "Molten Sphere"],
  ["Activator Cube", "Lava Cube", "White Cube"],
  ["Cooled Lava Cube", "Lava Cube", "Glacier Cube"],
  ["Power Cube", "Cooled Lava Cube", "Plasma Cube"],
  ["Charged Power Cube", "Power Fragment", "Power Cube"],
  ["Super-Charged Power Cube", "Charged Power Cube", "Goldplate Cube"],
  ["Contained Super-Charged Power Cube", "Power Cube Cage", "Super-Charged Power Cube"],

  ["Permafrost Cube", "Glacier Cube", "Glacier Cube"],
  ["Glacier Cube", "Ice Cube", "Water Cube"],
  ["Sand Cube", "Steam Cube", "Rock Cube"],
  ["Wet Sand Cube", "Sand Cube", "Water Cube"],
  ["Mud Cube", "Dirt Cube", "Water Cube"],
  ["Soil Cube", "Mud Cube", "Green Cube"],
  ["Grass Cube", "Soil Cube", "Green Cube"],
  ["Flower Cube", "Grass Cube", "Magenta Cube"],
  ["Blossom Cube", "Flower Cube", "Enricher"],

  ["Wet Concrete Cube", "Mud Cube", "Wet Sand Cube"],
  ["Acid Cube", "Water Cube", "Plasma Cube"],
  ["Energy Cube", "Lava Cube", "Plasma Cube"],
  ["Light Cube", "Energy Cube", "Copper Cube"],

  ["Copper Cube", "White Cube", "Copper"],
  ["Iron Cube", "White Cube", "Iron"],
  ["Gold Cube", "White Cube", "Gold"],
  ["Pyrolite Cube", "White Cube", "Pyrolite"],
  ["Rusted Iron", "Steam Cube", "Iron"],
  ["Rusted Iron Cube", "Steam Cube", "Iron Cube"],
  ["Rusted Iron Cube", "White Cube", "Rusted Iron"],
  ["Slightly Oxidised Copper Cube", "White Cube", "Slightly Oxidised Copper"],
  ["Heavily Oxidised Copper Cube", "White Cube", "Heavily Oxidised Copper"],

  ["Air Cube", "Steam Cube", "White Cube"],
  ["Dash Cube", "Air Cube", "Cyan Cube"],

  ["Forge Cube", "Gold Cube", "Iron Cube"],
  ["Plate Cube", "Forge Cube", "Iron Cube"],
  ["Power Cube Cage", "Plate Cube", "Iron Cube"],
  ["Metalic Cube", "Forge Cube", "Plate Cube"],
  ["Pusher", "Metalic Cube", "Stick"],
  ["Battery Cube", "Plate Cube", "Acid Cube"],
  ["Charged Battery Cube", "Battery Cube", "Charged Power Cube"],
  ["Teleportation Pad", "Concrete Barricade", "Charged Battery Cube"],
  ["Wealth Cube", "Forge Cube", "Gold Cube"],
  ["Goldplate Cube", "Wealth Cube", "Plate Cube"],
  ["Enricher", "Goldplate Cube", "Cooled Lava Cube"],
  ["Enrichment Cube", "Enricher", "Wealth Cube"],
  ["Enriched Pyrolite", "Enricher", "Pyrolite"],
  ["Gilded Stick", "Enrichment Cube", "Stick"],

  ["Healer Cube", "Plate Cube", "Green Cube"],
  ["Life Cube", "Healer Cube", "Enrichment Cube"],
  ["Soul Cube", "Life Cube", "Power Cube"],
  ["Cruelty Cube", "Soul Cube", "Death Cube"],
  ["Max Health Increaser", "Life Cube", "Healer Cube"],
  ["Max Health Decreaser", "Max Health Increaser", "Death Cube"],
  ["Regen Cube", "Healer Cube", "Wealth Cube"],
  ["Restore Cube", "Regen Cube", "Enriched Green Cube"],
  ["Health Cube", "Regen Cube", "Healer Cube"],
  ["Regen Coil", "Regen Cube", "Forge Cube"],
  ["Restoration Coil", "Regen Cube", "Restore Cube"],

  ["Enriched Red Cube", "Wealth Cube", "Red Cube"],
  ["Enriched Green Cube", "Wealth Cube", "Green Cube"],
  ["Enriched Blue Cube", "Wealth Cube", "Blue Cube"],

  ["Sword", "Forge Cube", "Iron"],
  ["Golden Sword", "Sword", "Gold Cube"],
  ["Air Sword", "Golden Sword", "Air Cube"],
  ["Light Sword", "Golden Sword", "Light Cube"],
  ["Club", "Wood Cube", "Red Cube"],
  ["Reinforced Club", "Club", "Forge Cube"],
  ["Iron Club", "Reinforced Club", "Iron Cube"],
  ["Golden Club", "Reinforced Club", "Gold Cube"],
  ["Ice Club", "Iron Club", "Ice Cube"],
  ["Flaming Club", "Iron Club", "Lava Cube"],
  ["Goldfire Club", "Flaming Club", "Golden Club"],
  ["Glacier Club", "Ice Club", "Glacier Club"],
  ["Goldfire Club", "Goldfire Club", "Golden Club"],

  ["Concrete Barricade", "Concrete Cube", "Iron Cube"],
  ["Stone Barricade", "Rock Cube", "Iron Cube"],
  ["Wooden Barricade", "Wood Cube", "Iron Cube"],
  ["Metal Barricade", "Copper Cube", "Iron Cube"],
  ["Metal Wall", "Metal Barricade", "Plate Cube"],
  ["Metal Window Wall", "Metal Wall", "Green Cube"],
  ["Lantern", "Wooden Barricade", "Light Cube"],
  ["Hammer", "Wood Cube", "Iron"],

  ["Ally Cube", "Wealth Cube", "Power Cube"],
  ["Speed Coil", "Forge Cube", "Red Cube"],
  ["Gravity Coil", "Forge Cube", "Blue Cube"],
  ["Fusion Coil", "Speed Coil", "Gravity Coil"],
  ["Enriched Speed Coil", "Speed Coil", "Enriched Red Cube"],
  ["Enriched Gravity Coil", "Gravity Coil", "Enriched Blue Cube"],
  ["Conveyor Belt", "Speed Coil", "Copper Cube"],
  ["Alternating Conveyor Belt", "Conveyor Belt", "Purple Cube"],
  ["Sledgehammer", "Stick", "Plate Cube",],
  ["Bridger", "Wood Cube", "Plate Cube",],


  ["Blade", "Forge Cube", "Copper"],
  ["Sword", "Blade", "Wood Cube"],
  ["Pyrolite Sword", "Sword", "Pyrolite Cube"],
  ["Heavy Hammer", "Forge Cube", "Hammer"],

  ["Stick", "Forge Cube", "Wood Cube"],
  ["Ladder", "Stick", "Wooden Barricade"],

  ["Corruption Cube", "Corruption", "White Cube"],
  ["Chromium Cube", "Chromium", "White Cube"],
  ["Flesh Barricade", "Chromium Cube", "Flesh Cube"],
  ["Flesh Wall", "Plate Cube", "Flesh Barricade"],
  ["Stone Wall", "Plate Cube", "Stone Barricade"],
  ["Stone Window Wall", "Stone Wall", "Green Cube"],
  ["Wooden Wall", "Plate Cube", "Wooden Barricade"],
  [ashProcess, "Wooden Wall", "Soil Cube"],
  ["Concrete Wall", "Plate Cube", "Concrete Barricade"],
  ["Reinforced Concrete Wall", "Concrete Wall", "Concrete Barricade"],

  ["Chromium Ring", "Chromium Cube", "Chromium"],
  ["Semi-Powerful Magic Crystal", "Magic Crystal", "Magic Crystal"],
  [
    "Powerful Magic Crystal",
    "Semi-Powerful Magic Crystal",
    "Semi-Powerful Magic Crystal",
  ],
  ["Mage Staff", "Powerful Magic Crystal", "Stick"],
  ["Charged Mage Staff", "Mage Staff", "Charged Power Cube"],
  ["Charged Healer Staff", "Charged Mage Staff", "Regen Cube"],

  ["Throwable Cube", "Iron", "Red Cube"],
  ["Explosive Cube", "Throwable Cube", "Gunpowder Cube"],
  ["Bomb Cube", "Explosive Cube", "Lava Cube"],
  ["Impact Cube", "Explosive Cube", "Enrichment Cube"],
  ["Impact Bomb Cube", "Impact Cube", "Bomb Cube"],

  [emptyItem, "Ash Cube", furnaceProcess],
  ["Dirt Cube", "Mud Cube", furnaceProcess],
  ["Glacier Cube", "Permafrost Cube", furnaceProcess],
  ["Ice Cube", "Glacier Cube", furnaceProcess],
  ["Water Cube", "Ice Cube", furnaceProcess],
  ["Steam Cube", "Water Cube", furnaceProcess],
  ["Plasma Cube", "Steam Cube", furnaceProcess],
  ["Copper", "Dirt Cube", furnaceProcess],
  ["Iron", "Dirt Cube", furnaceProcess],
  ["Gold", "Dirt Cube", furnaceProcess],
  ["Pyrolite", "Dirt Cube", furnaceProcess],
  ["Black Cube", "White Cube", furnaceProcess],
  ["Corruption", "Crimson Cube", furnaceProcess],
  ["Chromium", "Crimson Cube", furnaceProcess],
  ["Orb Of Crimson", "Crimson Cube", furnaceProcess],
  ["Death Cube", "Pain Cube", furnaceProcess],
  ["Molten Sphere", "Rock Cube", furnaceProcess],
  ["Molten Sphere", "Copper", furnaceProcess],
  ["Molten Sphere", "Iron", furnaceProcess],
  ["Molten Sphere", "Rusted Iron", furnaceProcess],
  ["Molten Sphere", "Gold", furnaceProcess],
  ["Molten Sphere", "Slightly Oxidised Copper", furnaceProcess],
  ["Molten Sphere", "Heavily Oxidised Copper", furnaceProcess],
  ["Molten Sphere", "Copper Cube", furnaceProcess],
  ["Molten Sphere", "Iron Cube", furnaceProcess],
  ["Molten Sphere", "Rusted Iron Cube", furnaceProcess],
  ["Molten Sphere", "Gold Cube", furnaceProcess],
  ["Molten Sphere", "Slightly Oxidised Copper Cube", furnaceProcess],
  ["Molten Sphere", "Heavily Oxidised Copper Cube", furnaceProcess],
  ["Molten Sphere", "Corruption", furnaceProcess],
  ["Molten Sphere", "Corruption Cube", furnaceProcess],
  ["Molten Sphere", "Chromium", furnaceProcess],
  ["Molten Sphere", "Chromium Cube", furnaceProcess],
  ["Power Fragment", "Power Cube", furnaceProcess],
  ["Concrete Cube", "Wet Concrete Cube", furnaceProcess],
  ["Gunpowder Cube", "Sand Cube", furnaceProcess],

  ["Slightly Oxidised Copper", "Copper", timeProcess],
  ["Heavily Oxidised Copper", "Slightly Oxidised Copper", timeProcess],
  ["Slightly Oxidised Copper Cube", "Copper Cube", timeProcess],
  ["Heavily Oxidised Copper Cube", "Slightly Oxidised Copper Cube", timeProcess],

  ["Mud Cube", "Ash Cube", ashProcess], // requires Water Cube
  ["Sand Cube", "Ash Cube", ashProcess], // requires Water Cube
  ["Forge Cube", "Ash Cube", ashProcess], // requires Water Cube

  ["Dirt Cube", "Ash Cube", ashProcess],
  ["Rock Cube", "Ash Cube", ashProcess],
  ["Gold", "Ash Cube", ashProcess],
  ["Iron", "Ash Cube", ashProcess],
  ["Copper", "Ash Cube", ashProcess],
  ["Gunpowder", "Ash Cube", ashProcess],
  ["White Cube", "Ash Cube", ashProcess],
]);